/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoisRouteImport } from './routes/whois'
import { Route as UuidRouteImport } from './routes/uuid'
import { Route as UrlEncodeRouteImport } from './routes/url-encode'
import { Route as TextSortRouteImport } from './routes/text-sort'
import { Route as ServerEnvRouteImport } from './routes/server-env'
import { Route as RegexCheckerRouteImport } from './routes/regex-checker'
import { Route as PasswordGeneratorRouteImport } from './routes/password-generator'
import { Route as OgpRouteImport } from './routes/ogp'
import { Route as JwtRouteImport } from './routes/jwt'
import { Route as JsonRouteImport } from './routes/json'
import { Route as IpGeolocationRouteImport } from './routes/ip-geolocation'
import { Route as ImageToGifRouteImport } from './routes/image-to-gif'
import { Route as HashRouteImport } from './routes/hash'
import { Route as GlobalIpRouteImport } from './routes/global-ip'
import { Route as EmailDnsRouteImport } from './routes/email-dns'
import { Route as DummyImageRouteImport } from './routes/dummy-image'
import { Route as DummyAudioRouteImport } from './routes/dummy-audio'
import { Route as DiceRollRouteImport } from './routes/dice-roll'
import { Route as ColorExtractorRouteImport } from './routes/color-extractor'
import { Route as CharCountRouteImport } from './routes/char-count'
import { Route as Base64RouteImport } from './routes/base64'
import { Route as AudioConverterRouteImport } from './routes/audio-converter'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiImageDotwebpRouteImport } from './routes/api/image[.]webp'
import { Route as ApiImageDotsvgRouteImport } from './routes/api/image[.]svg'
import { Route as ApiImageDotpngRouteImport } from './routes/api/image[.]png'
import { Route as ApiImageDotjpgRouteImport } from './routes/api/image[.]jpg'

const WhoisRoute = WhoisRouteImport.update({
  id: '/whois',
  path: '/whois',
  getParentRoute: () => rootRouteImport,
} as any)
const UuidRoute = UuidRouteImport.update({
  id: '/uuid',
  path: '/uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlEncodeRoute = UrlEncodeRouteImport.update({
  id: '/url-encode',
  path: '/url-encode',
  getParentRoute: () => rootRouteImport,
} as any)
const TextSortRoute = TextSortRouteImport.update({
  id: '/text-sort',
  path: '/text-sort',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerEnvRoute = ServerEnvRouteImport.update({
  id: '/server-env',
  path: '/server-env',
  getParentRoute: () => rootRouteImport,
} as any)
const RegexCheckerRoute = RegexCheckerRouteImport.update({
  id: '/regex-checker',
  path: '/regex-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordGeneratorRoute = PasswordGeneratorRouteImport.update({
  id: '/password-generator',
  path: '/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const OgpRoute = OgpRouteImport.update({
  id: '/ogp',
  path: '/ogp',
  getParentRoute: () => rootRouteImport,
} as any)
const JwtRoute = JwtRouteImport.update({
  id: '/jwt',
  path: '/jwt',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonRoute = JsonRouteImport.update({
  id: '/json',
  path: '/json',
  getParentRoute: () => rootRouteImport,
} as any)
const IpGeolocationRoute = IpGeolocationRouteImport.update({
  id: '/ip-geolocation',
  path: '/ip-geolocation',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToGifRoute = ImageToGifRouteImport.update({
  id: '/image-to-gif',
  path: '/image-to-gif',
  getParentRoute: () => rootRouteImport,
} as any)
const HashRoute = HashRouteImport.update({
  id: '/hash',
  path: '/hash',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalIpRoute = GlobalIpRouteImport.update({
  id: '/global-ip',
  path: '/global-ip',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailDnsRoute = EmailDnsRouteImport.update({
  id: '/email-dns',
  path: '/email-dns',
  getParentRoute: () => rootRouteImport,
} as any)
const DummyImageRoute = DummyImageRouteImport.update({
  id: '/dummy-image',
  path: '/dummy-image',
  getParentRoute: () => rootRouteImport,
} as any)
const DummyAudioRoute = DummyAudioRouteImport.update({
  id: '/dummy-audio',
  path: '/dummy-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const DiceRollRoute = DiceRollRouteImport.update({
  id: '/dice-roll',
  path: '/dice-roll',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorExtractorRoute = ColorExtractorRouteImport.update({
  id: '/color-extractor',
  path: '/color-extractor',
  getParentRoute: () => rootRouteImport,
} as any)
const CharCountRoute = CharCountRouteImport.update({
  id: '/char-count',
  path: '/char-count',
  getParentRoute: () => rootRouteImport,
} as any)
const Base64Route = Base64RouteImport.update({
  id: '/base64',
  path: '/base64',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioConverterRoute = AudioConverterRouteImport.update({
  id: '/audio-converter',
  path: '/audio-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageDotwebpRoute = ApiImageDotwebpRouteImport.update({
  id: '/api/image.webp',
  path: '/api/image.webp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageDotsvgRoute = ApiImageDotsvgRouteImport.update({
  id: '/api/image.svg',
  path: '/api/image.svg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageDotpngRoute = ApiImageDotpngRouteImport.update({
  id: '/api/image.png',
  path: '/api/image.png',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageDotjpgRoute = ApiImageDotjpgRouteImport.update({
  id: '/api/image.jpg',
  path: '/api/image.jpg',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio-converter': typeof AudioConverterRoute
  '/base64': typeof Base64Route
  '/char-count': typeof CharCountRoute
  '/color-extractor': typeof ColorExtractorRoute
  '/dice-roll': typeof DiceRollRoute
  '/dummy-audio': typeof DummyAudioRoute
  '/dummy-image': typeof DummyImageRoute
  '/email-dns': typeof EmailDnsRoute
  '/global-ip': typeof GlobalIpRoute
  '/hash': typeof HashRoute
  '/image-to-gif': typeof ImageToGifRoute
  '/ip-geolocation': typeof IpGeolocationRoute
  '/json': typeof JsonRoute
  '/jwt': typeof JwtRoute
  '/ogp': typeof OgpRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/regex-checker': typeof RegexCheckerRoute
  '/server-env': typeof ServerEnvRoute
  '/text-sort': typeof TextSortRoute
  '/url-encode': typeof UrlEncodeRoute
  '/uuid': typeof UuidRoute
  '/whois': typeof WhoisRoute
  '/api/image.jpg': typeof ApiImageDotjpgRoute
  '/api/image.png': typeof ApiImageDotpngRoute
  '/api/image.svg': typeof ApiImageDotsvgRoute
  '/api/image.webp': typeof ApiImageDotwebpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio-converter': typeof AudioConverterRoute
  '/base64': typeof Base64Route
  '/char-count': typeof CharCountRoute
  '/color-extractor': typeof ColorExtractorRoute
  '/dice-roll': typeof DiceRollRoute
  '/dummy-audio': typeof DummyAudioRoute
  '/dummy-image': typeof DummyImageRoute
  '/email-dns': typeof EmailDnsRoute
  '/global-ip': typeof GlobalIpRoute
  '/hash': typeof HashRoute
  '/image-to-gif': typeof ImageToGifRoute
  '/ip-geolocation': typeof IpGeolocationRoute
  '/json': typeof JsonRoute
  '/jwt': typeof JwtRoute
  '/ogp': typeof OgpRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/regex-checker': typeof RegexCheckerRoute
  '/server-env': typeof ServerEnvRoute
  '/text-sort': typeof TextSortRoute
  '/url-encode': typeof UrlEncodeRoute
  '/uuid': typeof UuidRoute
  '/whois': typeof WhoisRoute
  '/api/image.jpg': typeof ApiImageDotjpgRoute
  '/api/image.png': typeof ApiImageDotpngRoute
  '/api/image.svg': typeof ApiImageDotsvgRoute
  '/api/image.webp': typeof ApiImageDotwebpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio-converter': typeof AudioConverterRoute
  '/base64': typeof Base64Route
  '/char-count': typeof CharCountRoute
  '/color-extractor': typeof ColorExtractorRoute
  '/dice-roll': typeof DiceRollRoute
  '/dummy-audio': typeof DummyAudioRoute
  '/dummy-image': typeof DummyImageRoute
  '/email-dns': typeof EmailDnsRoute
  '/global-ip': typeof GlobalIpRoute
  '/hash': typeof HashRoute
  '/image-to-gif': typeof ImageToGifRoute
  '/ip-geolocation': typeof IpGeolocationRoute
  '/json': typeof JsonRoute
  '/jwt': typeof JwtRoute
  '/ogp': typeof OgpRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/regex-checker': typeof RegexCheckerRoute
  '/server-env': typeof ServerEnvRoute
  '/text-sort': typeof TextSortRoute
  '/url-encode': typeof UrlEncodeRoute
  '/uuid': typeof UuidRoute
  '/whois': typeof WhoisRoute
  '/api/image.jpg': typeof ApiImageDotjpgRoute
  '/api/image.png': typeof ApiImageDotpngRoute
  '/api/image.svg': typeof ApiImageDotsvgRoute
  '/api/image.webp': typeof ApiImageDotwebpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio-converter'
    | '/base64'
    | '/char-count'
    | '/color-extractor'
    | '/dice-roll'
    | '/dummy-audio'
    | '/dummy-image'
    | '/email-dns'
    | '/global-ip'
    | '/hash'
    | '/image-to-gif'
    | '/ip-geolocation'
    | '/json'
    | '/jwt'
    | '/ogp'
    | '/password-generator'
    | '/regex-checker'
    | '/server-env'
    | '/text-sort'
    | '/url-encode'
    | '/uuid'
    | '/whois'
    | '/api/image.jpg'
    | '/api/image.png'
    | '/api/image.svg'
    | '/api/image.webp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio-converter'
    | '/base64'
    | '/char-count'
    | '/color-extractor'
    | '/dice-roll'
    | '/dummy-audio'
    | '/dummy-image'
    | '/email-dns'
    | '/global-ip'
    | '/hash'
    | '/image-to-gif'
    | '/ip-geolocation'
    | '/json'
    | '/jwt'
    | '/ogp'
    | '/password-generator'
    | '/regex-checker'
    | '/server-env'
    | '/text-sort'
    | '/url-encode'
    | '/uuid'
    | '/whois'
    | '/api/image.jpg'
    | '/api/image.png'
    | '/api/image.svg'
    | '/api/image.webp'
  id:
    | '__root__'
    | '/'
    | '/audio-converter'
    | '/base64'
    | '/char-count'
    | '/color-extractor'
    | '/dice-roll'
    | '/dummy-audio'
    | '/dummy-image'
    | '/email-dns'
    | '/global-ip'
    | '/hash'
    | '/image-to-gif'
    | '/ip-geolocation'
    | '/json'
    | '/jwt'
    | '/ogp'
    | '/password-generator'
    | '/regex-checker'
    | '/server-env'
    | '/text-sort'
    | '/url-encode'
    | '/uuid'
    | '/whois'
    | '/api/image.jpg'
    | '/api/image.png'
    | '/api/image.svg'
    | '/api/image.webp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioConverterRoute: typeof AudioConverterRoute
  Base64Route: typeof Base64Route
  CharCountRoute: typeof CharCountRoute
  ColorExtractorRoute: typeof ColorExtractorRoute
  DiceRollRoute: typeof DiceRollRoute
  DummyAudioRoute: typeof DummyAudioRoute
  DummyImageRoute: typeof DummyImageRoute
  EmailDnsRoute: typeof EmailDnsRoute
  GlobalIpRoute: typeof GlobalIpRoute
  HashRoute: typeof HashRoute
  ImageToGifRoute: typeof ImageToGifRoute
  IpGeolocationRoute: typeof IpGeolocationRoute
  JsonRoute: typeof JsonRoute
  JwtRoute: typeof JwtRoute
  OgpRoute: typeof OgpRoute
  PasswordGeneratorRoute: typeof PasswordGeneratorRoute
  RegexCheckerRoute: typeof RegexCheckerRoute
  ServerEnvRoute: typeof ServerEnvRoute
  TextSortRoute: typeof TextSortRoute
  UrlEncodeRoute: typeof UrlEncodeRoute
  UuidRoute: typeof UuidRoute
  WhoisRoute: typeof WhoisRoute
  ApiImageDotjpgRoute: typeof ApiImageDotjpgRoute
  ApiImageDotpngRoute: typeof ApiImageDotpngRoute
  ApiImageDotsvgRoute: typeof ApiImageDotsvgRoute
  ApiImageDotwebpRoute: typeof ApiImageDotwebpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whois': {
      id: '/whois'
      path: '/whois'
      fullPath: '/whois'
      preLoaderRoute: typeof WhoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uuid': {
      id: '/uuid'
      path: '/uuid'
      fullPath: '/uuid'
      preLoaderRoute: typeof UuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url-encode': {
      id: '/url-encode'
      path: '/url-encode'
      fullPath: '/url-encode'
      preLoaderRoute: typeof UrlEncodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-sort': {
      id: '/text-sort'
      path: '/text-sort'
      fullPath: '/text-sort'
      preLoaderRoute: typeof TextSortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-env': {
      id: '/server-env'
      path: '/server-env'
      fullPath: '/server-env'
      preLoaderRoute: typeof ServerEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regex-checker': {
      id: '/regex-checker'
      path: '/regex-checker'
      fullPath: '/regex-checker'
      preLoaderRoute: typeof RegexCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-generator': {
      id: '/password-generator'
      path: '/password-generator'
      fullPath: '/password-generator'
      preLoaderRoute: typeof PasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ogp': {
      id: '/ogp'
      path: '/ogp'
      fullPath: '/ogp'
      preLoaderRoute: typeof OgpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwt': {
      id: '/jwt'
      path: '/jwt'
      fullPath: '/jwt'
      preLoaderRoute: typeof JwtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json': {
      id: '/json'
      path: '/json'
      fullPath: '/json'
      preLoaderRoute: typeof JsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-geolocation': {
      id: '/ip-geolocation'
      path: '/ip-geolocation'
      fullPath: '/ip-geolocation'
      preLoaderRoute: typeof IpGeolocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-gif': {
      id: '/image-to-gif'
      path: '/image-to-gif'
      fullPath: '/image-to-gif'
      preLoaderRoute: typeof ImageToGifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash': {
      id: '/hash'
      path: '/hash'
      fullPath: '/hash'
      preLoaderRoute: typeof HashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-ip': {
      id: '/global-ip'
      path: '/global-ip'
      fullPath: '/global-ip'
      preLoaderRoute: typeof GlobalIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-dns': {
      id: '/email-dns'
      path: '/email-dns'
      fullPath: '/email-dns'
      preLoaderRoute: typeof EmailDnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dummy-image': {
      id: '/dummy-image'
      path: '/dummy-image'
      fullPath: '/dummy-image'
      preLoaderRoute: typeof DummyImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dummy-audio': {
      id: '/dummy-audio'
      path: '/dummy-audio'
      fullPath: '/dummy-audio'
      preLoaderRoute: typeof DummyAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dice-roll': {
      id: '/dice-roll'
      path: '/dice-roll'
      fullPath: '/dice-roll'
      preLoaderRoute: typeof DiceRollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-extractor': {
      id: '/color-extractor'
      path: '/color-extractor'
      fullPath: '/color-extractor'
      preLoaderRoute: typeof ColorExtractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/char-count': {
      id: '/char-count'
      path: '/char-count'
      fullPath: '/char-count'
      preLoaderRoute: typeof CharCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base64': {
      id: '/base64'
      path: '/base64'
      fullPath: '/base64'
      preLoaderRoute: typeof Base64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-converter': {
      id: '/audio-converter'
      path: '/audio-converter'
      fullPath: '/audio-converter'
      preLoaderRoute: typeof AudioConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image.webp': {
      id: '/api/image.webp'
      path: '/api/image.webp'
      fullPath: '/api/image.webp'
      preLoaderRoute: typeof ApiImageDotwebpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image.svg': {
      id: '/api/image.svg'
      path: '/api/image.svg'
      fullPath: '/api/image.svg'
      preLoaderRoute: typeof ApiImageDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image.png': {
      id: '/api/image.png'
      path: '/api/image.png'
      fullPath: '/api/image.png'
      preLoaderRoute: typeof ApiImageDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image.jpg': {
      id: '/api/image.jpg'
      path: '/api/image.jpg'
      fullPath: '/api/image.jpg'
      preLoaderRoute: typeof ApiImageDotjpgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioConverterRoute: AudioConverterRoute,
  Base64Route: Base64Route,
  CharCountRoute: CharCountRoute,
  ColorExtractorRoute: ColorExtractorRoute,
  DiceRollRoute: DiceRollRoute,
  DummyAudioRoute: DummyAudioRoute,
  DummyImageRoute: DummyImageRoute,
  EmailDnsRoute: EmailDnsRoute,
  GlobalIpRoute: GlobalIpRoute,
  HashRoute: HashRoute,
  ImageToGifRoute: ImageToGifRoute,
  IpGeolocationRoute: IpGeolocationRoute,
  JsonRoute: JsonRoute,
  JwtRoute: JwtRoute,
  OgpRoute: OgpRoute,
  PasswordGeneratorRoute: PasswordGeneratorRoute,
  RegexCheckerRoute: RegexCheckerRoute,
  ServerEnvRoute: ServerEnvRoute,
  TextSortRoute: TextSortRoute,
  UrlEncodeRoute: UrlEncodeRoute,
  UuidRoute: UuidRoute,
  WhoisRoute: WhoisRoute,
  ApiImageDotjpgRoute: ApiImageDotjpgRoute,
  ApiImageDotpngRoute: ApiImageDotpngRoute,
  ApiImageDotsvgRoute: ApiImageDotsvgRoute,
  ApiImageDotwebpRoute: ApiImageDotwebpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
