/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YamlJsonRouteImport } from './routes/yaml-json'
import { Route as XmlRouteImport } from './routes/xml'
import { Route as WhoisRouteImport } from './routes/whois'
import { Route as VideoConverterRouteImport } from './routes/video-converter'
import { Route as UuidRouteImport } from './routes/uuid'
import { Route as UserAgentRouteImport } from './routes/user-agent'
import { Route as UrlParserRouteImport } from './routes/url-parser'
import { Route as UrlEncodeRouteImport } from './routes/url-encode'
import { Route as UnitConverterRouteImport } from './routes/unit-converter'
import { Route as UnicodeRouteImport } from './routes/unicode'
import { Route as TypographyScaleRouteImport } from './routes/typography-scale'
import { Route as TransparentImageRouteImport } from './routes/transparent-image'
import { Route as TotpRouteImport } from './routes/totp'
import { Route as TopRouteImport } from './routes/top'
import { Route as TomlJsonRouteImport } from './routes/toml-json'
import { Route as TimezoneRouteImport } from './routes/timezone'
import { Route as TimestampRouteImport } from './routes/timestamp'
import { Route as TextStatsRouteImport } from './routes/text-stats'
import { Route as TextSortRouteImport } from './routes/text-sort'
import { Route as TextReplaceRouteImport } from './routes/text-replace'
import { Route as TextEncryptRouteImport } from './routes/text-encrypt'
import { Route as TextCaseRouteImport } from './routes/text-case'
import { Route as SvgOptimizerRouteImport } from './routes/svg-optimizer'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as SlugRouteImport } from './routes/slug'
import { Route as ServerEnvRouteImport } from './routes/server-env'
import { Route as SecurityHeadersRouteImport } from './routes/security-headers'
import { Route as RobotsTxtRouteImport } from './routes/robots-txt'
import { Route as RegexCheckerRouteImport } from './routes/regex-checker'
import { Route as RandomDataRouteImport } from './routes/random-data'
import { Route as QrCodeRouteImport } from './routes/qr-code'
import { Route as PortCheckRouteImport } from './routes/port-check'
import { Route as PomodoroRouteImport } from './routes/pomodoro'
import { Route as PhpSerializeRouteImport } from './routes/php-serialize'
import { Route as PasswordGeneratorRouteImport } from './routes/password-generator'
import { Route as OpensslBuilderRouteImport } from './routes/openssl-builder'
import { Route as OgpRouteImport } from './routes/ogp'
import { Route as NumberBaseRouteImport } from './routes/number-base'
import { Route as MsgpackRouteImport } from './routes/msgpack'
import { Route as MorseCodeRouteImport } from './routes/morse-code'
import { Route as MinifyRouteImport } from './routes/minify'
import { Route as MimeTypesRouteImport } from './routes/mime-types'
import { Route as MermaidRouteImport } from './routes/mermaid'
import { Route as MathEvalRouteImport } from './routes/math-eval'
import { Route as MarkdownTableRouteImport } from './routes/markdown-table'
import { Route as MarkdownPreviewRouteImport } from './routes/markdown-preview'
import { Route as LoremIpsumRouteImport } from './routes/lorem-ipsum'
import { Route as KeycodeRouteImport } from './routes/keycode'
import { Route as JwtGeneratorRouteImport } from './routes/jwt-generator'
import { Route as JwtRouteImport } from './routes/jwt'
import { Route as JsonToTsRouteImport } from './routes/json-to-ts'
import { Route as JsonSchemaRouteImport } from './routes/json-schema'
import { Route as JsonPathRouteImport } from './routes/json-path'
import { Route as JsonCompareRouteImport } from './routes/json-compare'
import { Route as JsonRouteImport } from './routes/json'
import { Route as IpGeolocationRouteImport } from './routes/ip-geolocation'
import { Route as IpConverterRouteImport } from './routes/ip-converter'
import { Route as IpCidrCheckRouteImport } from './routes/ip-cidr-check'
import { Route as ImageToGifRouteImport } from './routes/image-to-gif'
import { Route as ImageResizeRouteImport } from './routes/image-resize'
import { Route as ImageCropRouteImport } from './routes/image-crop'
import { Route as ImageCompressRouteImport } from './routes/image-compress'
import { Route as ImageBase64RouteImport } from './routes/image-base64'
import { Route as HttpStatusRouteImport } from './routes/http-status'
import { Route as HttpHeadersRouteImport } from './routes/http-headers'
import { Route as HttpClientRouteImport } from './routes/http-client'
import { Route as HtmlToJsxRouteImport } from './routes/html-to-jsx'
import { Route as HtmlEncodeRouteImport } from './routes/html-encode'
import { Route as HexViewerRouteImport } from './routes/hex-viewer'
import { Route as HashRouteImport } from './routes/hash'
import { Route as GlobalIpRouteImport } from './routes/global-ip'
import { Route as GitignoreRouteImport } from './routes/gitignore'
import { Route as FaviconGeneratorRouteImport } from './routes/favicon-generator'
import { Route as EnvParserRouteImport } from './routes/env-parser'
import { Route as EmojiConverterRouteImport } from './routes/emoji-converter'
import { Route as EmailDnsRouteImport } from './routes/email-dns'
import { Route as DummyImageRouteImport } from './routes/dummy-image'
import { Route as DummyAudioRouteImport } from './routes/dummy-audio'
import { Route as DnsLookupRouteImport } from './routes/dns-lookup'
import { Route as DiscordStickerRouteImport } from './routes/discord-sticker'
import { Route as DiscordEmojiRouteImport } from './routes/discord-emoji'
import { Route as DiffRouteImport } from './routes/diff'
import { Route as DiceRollRouteImport } from './routes/dice-roll'
import { Route as CurlBuilderRouteImport } from './routes/curl-builder'
import { Route as CsvJsonRouteImport } from './routes/csv-json'
import { Route as CssUnitRouteImport } from './routes/css-unit'
import { Route as CssTransformRouteImport } from './routes/css-transform'
import { Route as CssTextShadowRouteImport } from './routes/css-text-shadow'
import { Route as CssSpecificityRouteImport } from './routes/css-specificity'
import { Route as CssGridRouteImport } from './routes/css-grid'
import { Route as CssGradientRouteImport } from './routes/css-gradient'
import { Route as CssFlexboxRouteImport } from './routes/css-flexbox'
import { Route as CssFilterRouteImport } from './routes/css-filter'
import { Route as CssClipPathRouteImport } from './routes/css-clip-path'
import { Route as CssBoxShadowRouteImport } from './routes/css-box-shadow'
import { Route as CssBorderRadiusRouteImport } from './routes/css-border-radius'
import { Route as CssAnimationRouteImport } from './routes/css-animation'
import { Route as CronParserRouteImport } from './routes/cron-parser'
import { Route as CronRouteImport } from './routes/cron'
import { Route as CookieParserRouteImport } from './routes/cookie-parser'
import { Route as ColorPickerRouteImport } from './routes/color-picker'
import { Route as ColorPaletteRouteImport } from './routes/color-palette'
import { Route as ColorHarmonyRouteImport } from './routes/color-harmony'
import { Route as ColorExtractorRouteImport } from './routes/color-extractor'
import { Route as ColorConverterRouteImport } from './routes/color-converter'
import { Route as ColorContrastRouteImport } from './routes/color-contrast'
import { Route as ColorBlindRouteImport } from './routes/color-blind'
import { Route as CidrRouteImport } from './routes/cidr'
import { Route as ChmodRouteImport } from './routes/chmod'
import { Route as CharCountRouteImport } from './routes/char-count'
import { Route as BitwiseRouteImport } from './routes/bitwise'
import { Route as Base64ImageRouteImport } from './routes/base64-image'
import { Route as Base64RouteImport } from './routes/base64'
import { Route as BarcodeRouteImport } from './routes/barcode'
import { Route as AudioConverterRouteImport } from './routes/audio-converter'
import { Route as AspectRatioRouteImport } from './routes/aspect-ratio'
import { Route as AsciiArtRouteImport } from './routes/ascii-art'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiImageDotwebpRouteImport } from './routes/api/image[.]webp'
import { Route as ApiImageDotsvgRouteImport } from './routes/api/image[.]svg'
import { Route as ApiImageDotpngRouteImport } from './routes/api/image[.]png'
import { Route as ApiImageDotjpgRouteImport } from './routes/api/image[.]jpg'

const YamlJsonRoute = YamlJsonRouteImport.update({
  id: '/yaml-json',
  path: '/yaml-json',
  getParentRoute: () => rootRouteImport,
} as any)
const XmlRoute = XmlRouteImport.update({
  id: '/xml',
  path: '/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoisRoute = WhoisRouteImport.update({
  id: '/whois',
  path: '/whois',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoConverterRoute = VideoConverterRouteImport.update({
  id: '/video-converter',
  path: '/video-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const UuidRoute = UuidRouteImport.update({
  id: '/uuid',
  path: '/uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAgentRoute = UserAgentRouteImport.update({
  id: '/user-agent',
  path: '/user-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlParserRoute = UrlParserRouteImport.update({
  id: '/url-parser',
  path: '/url-parser',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlEncodeRoute = UrlEncodeRouteImport.update({
  id: '/url-encode',
  path: '/url-encode',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitConverterRoute = UnitConverterRouteImport.update({
  id: '/unit-converter',
  path: '/unit-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const UnicodeRoute = UnicodeRouteImport.update({
  id: '/unicode',
  path: '/unicode',
  getParentRoute: () => rootRouteImport,
} as any)
const TypographyScaleRoute = TypographyScaleRouteImport.update({
  id: '/typography-scale',
  path: '/typography-scale',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparentImageRoute = TransparentImageRouteImport.update({
  id: '/transparent-image',
  path: '/transparent-image',
  getParentRoute: () => rootRouteImport,
} as any)
const TotpRoute = TotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => rootRouteImport,
} as any)
const TopRoute = TopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => rootRouteImport,
} as any)
const TomlJsonRoute = TomlJsonRouteImport.update({
  id: '/toml-json',
  path: '/toml-json',
  getParentRoute: () => rootRouteImport,
} as any)
const TimezoneRoute = TimezoneRouteImport.update({
  id: '/timezone',
  path: '/timezone',
  getParentRoute: () => rootRouteImport,
} as any)
const TimestampRoute = TimestampRouteImport.update({
  id: '/timestamp',
  path: '/timestamp',
  getParentRoute: () => rootRouteImport,
} as any)
const TextStatsRoute = TextStatsRouteImport.update({
  id: '/text-stats',
  path: '/text-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TextSortRoute = TextSortRouteImport.update({
  id: '/text-sort',
  path: '/text-sort',
  getParentRoute: () => rootRouteImport,
} as any)
const TextReplaceRoute = TextReplaceRouteImport.update({
  id: '/text-replace',
  path: '/text-replace',
  getParentRoute: () => rootRouteImport,
} as any)
const TextEncryptRoute = TextEncryptRouteImport.update({
  id: '/text-encrypt',
  path: '/text-encrypt',
  getParentRoute: () => rootRouteImport,
} as any)
const TextCaseRoute = TextCaseRouteImport.update({
  id: '/text-case',
  path: '/text-case',
  getParentRoute: () => rootRouteImport,
} as any)
const SvgOptimizerRoute = SvgOptimizerRouteImport.update({
  id: '/svg-optimizer',
  path: '/svg-optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/slug',
  path: '/slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerEnvRoute = ServerEnvRouteImport.update({
  id: '/server-env',
  path: '/server-env',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityHeadersRoute = SecurityHeadersRouteImport.update({
  id: '/security-headers',
  path: '/security-headers',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots-txt',
  path: '/robots-txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RegexCheckerRoute = RegexCheckerRouteImport.update({
  id: '/regex-checker',
  path: '/regex-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomDataRoute = RandomDataRouteImport.update({
  id: '/random-data',
  path: '/random-data',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeRoute = QrCodeRouteImport.update({
  id: '/qr-code',
  path: '/qr-code',
  getParentRoute: () => rootRouteImport,
} as any)
const PortCheckRoute = PortCheckRouteImport.update({
  id: '/port-check',
  path: '/port-check',
  getParentRoute: () => rootRouteImport,
} as any)
const PomodoroRoute = PomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => rootRouteImport,
} as any)
const PhpSerializeRoute = PhpSerializeRouteImport.update({
  id: '/php-serialize',
  path: '/php-serialize',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordGeneratorRoute = PasswordGeneratorRouteImport.update({
  id: '/password-generator',
  path: '/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const OpensslBuilderRoute = OpensslBuilderRouteImport.update({
  id: '/openssl-builder',
  path: '/openssl-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const OgpRoute = OgpRouteImport.update({
  id: '/ogp',
  path: '/ogp',
  getParentRoute: () => rootRouteImport,
} as any)
const NumberBaseRoute = NumberBaseRouteImport.update({
  id: '/number-base',
  path: '/number-base',
  getParentRoute: () => rootRouteImport,
} as any)
const MsgpackRoute = MsgpackRouteImport.update({
  id: '/msgpack',
  path: '/msgpack',
  getParentRoute: () => rootRouteImport,
} as any)
const MorseCodeRoute = MorseCodeRouteImport.update({
  id: '/morse-code',
  path: '/morse-code',
  getParentRoute: () => rootRouteImport,
} as any)
const MinifyRoute = MinifyRouteImport.update({
  id: '/minify',
  path: '/minify',
  getParentRoute: () => rootRouteImport,
} as any)
const MimeTypesRoute = MimeTypesRouteImport.update({
  id: '/mime-types',
  path: '/mime-types',
  getParentRoute: () => rootRouteImport,
} as any)
const MermaidRoute = MermaidRouteImport.update({
  id: '/mermaid',
  path: '/mermaid',
  getParentRoute: () => rootRouteImport,
} as any)
const MathEvalRoute = MathEvalRouteImport.update({
  id: '/math-eval',
  path: '/math-eval',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkdownTableRoute = MarkdownTableRouteImport.update({
  id: '/markdown-table',
  path: '/markdown-table',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkdownPreviewRoute = MarkdownPreviewRouteImport.update({
  id: '/markdown-preview',
  path: '/markdown-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoremIpsumRoute = LoremIpsumRouteImport.update({
  id: '/lorem-ipsum',
  path: '/lorem-ipsum',
  getParentRoute: () => rootRouteImport,
} as any)
const KeycodeRoute = KeycodeRouteImport.update({
  id: '/keycode',
  path: '/keycode',
  getParentRoute: () => rootRouteImport,
} as any)
const JwtGeneratorRoute = JwtGeneratorRouteImport.update({
  id: '/jwt-generator',
  path: '/jwt-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const JwtRoute = JwtRouteImport.update({
  id: '/jwt',
  path: '/jwt',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToTsRoute = JsonToTsRouteImport.update({
  id: '/json-to-ts',
  path: '/json-to-ts',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonSchemaRoute = JsonSchemaRouteImport.update({
  id: '/json-schema',
  path: '/json-schema',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonPathRoute = JsonPathRouteImport.update({
  id: '/json-path',
  path: '/json-path',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonCompareRoute = JsonCompareRouteImport.update({
  id: '/json-compare',
  path: '/json-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonRoute = JsonRouteImport.update({
  id: '/json',
  path: '/json',
  getParentRoute: () => rootRouteImport,
} as any)
const IpGeolocationRoute = IpGeolocationRouteImport.update({
  id: '/ip-geolocation',
  path: '/ip-geolocation',
  getParentRoute: () => rootRouteImport,
} as any)
const IpConverterRoute = IpConverterRouteImport.update({
  id: '/ip-converter',
  path: '/ip-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const IpCidrCheckRoute = IpCidrCheckRouteImport.update({
  id: '/ip-cidr-check',
  path: '/ip-cidr-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToGifRoute = ImageToGifRouteImport.update({
  id: '/image-to-gif',
  path: '/image-to-gif',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageResizeRoute = ImageResizeRouteImport.update({
  id: '/image-resize',
  path: '/image-resize',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCropRoute = ImageCropRouteImport.update({
  id: '/image-crop',
  path: '/image-crop',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCompressRoute = ImageCompressRouteImport.update({
  id: '/image-compress',
  path: '/image-compress',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageBase64Route = ImageBase64RouteImport.update({
  id: '/image-base64',
  path: '/image-base64',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpStatusRoute = HttpStatusRouteImport.update({
  id: '/http-status',
  path: '/http-status',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpHeadersRoute = HttpHeadersRouteImport.update({
  id: '/http-headers',
  path: '/http-headers',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpClientRoute = HttpClientRouteImport.update({
  id: '/http-client',
  path: '/http-client',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlToJsxRoute = HtmlToJsxRouteImport.update({
  id: '/html-to-jsx',
  path: '/html-to-jsx',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlEncodeRoute = HtmlEncodeRouteImport.update({
  id: '/html-encode',
  path: '/html-encode',
  getParentRoute: () => rootRouteImport,
} as any)
const HexViewerRoute = HexViewerRouteImport.update({
  id: '/hex-viewer',
  path: '/hex-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const HashRoute = HashRouteImport.update({
  id: '/hash',
  path: '/hash',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalIpRoute = GlobalIpRouteImport.update({
  id: '/global-ip',
  path: '/global-ip',
  getParentRoute: () => rootRouteImport,
} as any)
const GitignoreRoute = GitignoreRouteImport.update({
  id: '/gitignore',
  path: '/gitignore',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconGeneratorRoute = FaviconGeneratorRouteImport.update({
  id: '/favicon-generator',
  path: '/favicon-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvParserRoute = EnvParserRouteImport.update({
  id: '/env-parser',
  path: '/env-parser',
  getParentRoute: () => rootRouteImport,
} as any)
const EmojiConverterRoute = EmojiConverterRouteImport.update({
  id: '/emoji-converter',
  path: '/emoji-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailDnsRoute = EmailDnsRouteImport.update({
  id: '/email-dns',
  path: '/email-dns',
  getParentRoute: () => rootRouteImport,
} as any)
const DummyImageRoute = DummyImageRouteImport.update({
  id: '/dummy-image',
  path: '/dummy-image',
  getParentRoute: () => rootRouteImport,
} as any)
const DummyAudioRoute = DummyAudioRouteImport.update({
  id: '/dummy-audio',
  path: '/dummy-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsLookupRoute = DnsLookupRouteImport.update({
  id: '/dns-lookup',
  path: '/dns-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordStickerRoute = DiscordStickerRouteImport.update({
  id: '/discord-sticker',
  path: '/discord-sticker',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordEmojiRoute = DiscordEmojiRouteImport.update({
  id: '/discord-emoji',
  path: '/discord-emoji',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffRoute = DiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const DiceRollRoute = DiceRollRouteImport.update({
  id: '/dice-roll',
  path: '/dice-roll',
  getParentRoute: () => rootRouteImport,
} as any)
const CurlBuilderRoute = CurlBuilderRouteImport.update({
  id: '/curl-builder',
  path: '/curl-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CsvJsonRoute = CsvJsonRouteImport.update({
  id: '/csv-json',
  path: '/csv-json',
  getParentRoute: () => rootRouteImport,
} as any)
const CssUnitRoute = CssUnitRouteImport.update({
  id: '/css-unit',
  path: '/css-unit',
  getParentRoute: () => rootRouteImport,
} as any)
const CssTransformRoute = CssTransformRouteImport.update({
  id: '/css-transform',
  path: '/css-transform',
  getParentRoute: () => rootRouteImport,
} as any)
const CssTextShadowRoute = CssTextShadowRouteImport.update({
  id: '/css-text-shadow',
  path: '/css-text-shadow',
  getParentRoute: () => rootRouteImport,
} as any)
const CssSpecificityRoute = CssSpecificityRouteImport.update({
  id: '/css-specificity',
  path: '/css-specificity',
  getParentRoute: () => rootRouteImport,
} as any)
const CssGridRoute = CssGridRouteImport.update({
  id: '/css-grid',
  path: '/css-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const CssGradientRoute = CssGradientRouteImport.update({
  id: '/css-gradient',
  path: '/css-gradient',
  getParentRoute: () => rootRouteImport,
} as any)
const CssFlexboxRoute = CssFlexboxRouteImport.update({
  id: '/css-flexbox',
  path: '/css-flexbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CssFilterRoute = CssFilterRouteImport.update({
  id: '/css-filter',
  path: '/css-filter',
  getParentRoute: () => rootRouteImport,
} as any)
const CssClipPathRoute = CssClipPathRouteImport.update({
  id: '/css-clip-path',
  path: '/css-clip-path',
  getParentRoute: () => rootRouteImport,
} as any)
const CssBoxShadowRoute = CssBoxShadowRouteImport.update({
  id: '/css-box-shadow',
  path: '/css-box-shadow',
  getParentRoute: () => rootRouteImport,
} as any)
const CssBorderRadiusRoute = CssBorderRadiusRouteImport.update({
  id: '/css-border-radius',
  path: '/css-border-radius',
  getParentRoute: () => rootRouteImport,
} as any)
const CssAnimationRoute = CssAnimationRouteImport.update({
  id: '/css-animation',
  path: '/css-animation',
  getParentRoute: () => rootRouteImport,
} as any)
const CronParserRoute = CronParserRouteImport.update({
  id: '/cron-parser',
  path: '/cron-parser',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieParserRoute = CookieParserRouteImport.update({
  id: '/cookie-parser',
  path: '/cookie-parser',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorPickerRoute = ColorPickerRouteImport.update({
  id: '/color-picker',
  path: '/color-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorPaletteRoute = ColorPaletteRouteImport.update({
  id: '/color-palette',
  path: '/color-palette',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorHarmonyRoute = ColorHarmonyRouteImport.update({
  id: '/color-harmony',
  path: '/color-harmony',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorExtractorRoute = ColorExtractorRouteImport.update({
  id: '/color-extractor',
  path: '/color-extractor',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorConverterRoute = ColorConverterRouteImport.update({
  id: '/color-converter',
  path: '/color-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorContrastRoute = ColorContrastRouteImport.update({
  id: '/color-contrast',
  path: '/color-contrast',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorBlindRoute = ColorBlindRouteImport.update({
  id: '/color-blind',
  path: '/color-blind',
  getParentRoute: () => rootRouteImport,
} as any)
const CidrRoute = CidrRouteImport.update({
  id: '/cidr',
  path: '/cidr',
  getParentRoute: () => rootRouteImport,
} as any)
const ChmodRoute = ChmodRouteImport.update({
  id: '/chmod',
  path: '/chmod',
  getParentRoute: () => rootRouteImport,
} as any)
const CharCountRoute = CharCountRouteImport.update({
  id: '/char-count',
  path: '/char-count',
  getParentRoute: () => rootRouteImport,
} as any)
const BitwiseRoute = BitwiseRouteImport.update({
  id: '/bitwise',
  path: '/bitwise',
  getParentRoute: () => rootRouteImport,
} as any)
const Base64ImageRoute = Base64ImageRouteImport.update({
  id: '/base64-image',
  path: '/base64-image',
  getParentRoute: () => rootRouteImport,
} as any)
const Base64Route = Base64RouteImport.update({
  id: '/base64',
  path: '/base64',
  getParentRoute: () => rootRouteImport,
} as any)
const BarcodeRoute = BarcodeRouteImport.update({
  id: '/barcode',
  path: '/barcode',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioConverterRoute = AudioConverterRouteImport.update({
  id: '/audio-converter',
  path: '/audio-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const AspectRatioRoute = AspectRatioRouteImport.update({
  id: '/aspect-ratio',
  path: '/aspect-ratio',
  getParentRoute: () => rootRouteImport,
} as any)
const AsciiArtRoute = AsciiArtRouteImport.update({
  id: '/ascii-art',
  path: '/ascii-art',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageDotwebpRoute = ApiImageDotwebpRouteImport.update({
  id: '/api/image.webp',
  path: '/api/image.webp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageDotsvgRoute = ApiImageDotsvgRouteImport.update({
  id: '/api/image.svg',
  path: '/api/image.svg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageDotpngRoute = ApiImageDotpngRouteImport.update({
  id: '/api/image.png',
  path: '/api/image.png',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageDotjpgRoute = ApiImageDotjpgRouteImport.update({
  id: '/api/image.jpg',
  path: '/api/image.jpg',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ascii-art': typeof AsciiArtRoute
  '/aspect-ratio': typeof AspectRatioRoute
  '/audio-converter': typeof AudioConverterRoute
  '/barcode': typeof BarcodeRoute
  '/base64': typeof Base64Route
  '/base64-image': typeof Base64ImageRoute
  '/bitwise': typeof BitwiseRoute
  '/char-count': typeof CharCountRoute
  '/chmod': typeof ChmodRoute
  '/cidr': typeof CidrRoute
  '/color-blind': typeof ColorBlindRoute
  '/color-contrast': typeof ColorContrastRoute
  '/color-converter': typeof ColorConverterRoute
  '/color-extractor': typeof ColorExtractorRoute
  '/color-harmony': typeof ColorHarmonyRoute
  '/color-palette': typeof ColorPaletteRoute
  '/color-picker': typeof ColorPickerRoute
  '/cookie-parser': typeof CookieParserRoute
  '/cron': typeof CronRoute
  '/cron-parser': typeof CronParserRoute
  '/css-animation': typeof CssAnimationRoute
  '/css-border-radius': typeof CssBorderRadiusRoute
  '/css-box-shadow': typeof CssBoxShadowRoute
  '/css-clip-path': typeof CssClipPathRoute
  '/css-filter': typeof CssFilterRoute
  '/css-flexbox': typeof CssFlexboxRoute
  '/css-gradient': typeof CssGradientRoute
  '/css-grid': typeof CssGridRoute
  '/css-specificity': typeof CssSpecificityRoute
  '/css-text-shadow': typeof CssTextShadowRoute
  '/css-transform': typeof CssTransformRoute
  '/css-unit': typeof CssUnitRoute
  '/csv-json': typeof CsvJsonRoute
  '/curl-builder': typeof CurlBuilderRoute
  '/dice-roll': typeof DiceRollRoute
  '/diff': typeof DiffRoute
  '/discord-emoji': typeof DiscordEmojiRoute
  '/discord-sticker': typeof DiscordStickerRoute
  '/dns-lookup': typeof DnsLookupRoute
  '/dummy-audio': typeof DummyAudioRoute
  '/dummy-image': typeof DummyImageRoute
  '/email-dns': typeof EmailDnsRoute
  '/emoji-converter': typeof EmojiConverterRoute
  '/env-parser': typeof EnvParserRoute
  '/favicon-generator': typeof FaviconGeneratorRoute
  '/gitignore': typeof GitignoreRoute
  '/global-ip': typeof GlobalIpRoute
  '/hash': typeof HashRoute
  '/hex-viewer': typeof HexViewerRoute
  '/html-encode': typeof HtmlEncodeRoute
  '/html-to-jsx': typeof HtmlToJsxRoute
  '/http-client': typeof HttpClientRoute
  '/http-headers': typeof HttpHeadersRoute
  '/http-status': typeof HttpStatusRoute
  '/image-base64': typeof ImageBase64Route
  '/image-compress': typeof ImageCompressRoute
  '/image-crop': typeof ImageCropRoute
  '/image-resize': typeof ImageResizeRoute
  '/image-to-gif': typeof ImageToGifRoute
  '/ip-cidr-check': typeof IpCidrCheckRoute
  '/ip-converter': typeof IpConverterRoute
  '/ip-geolocation': typeof IpGeolocationRoute
  '/json': typeof JsonRoute
  '/json-compare': typeof JsonCompareRoute
  '/json-path': typeof JsonPathRoute
  '/json-schema': typeof JsonSchemaRoute
  '/json-to-ts': typeof JsonToTsRoute
  '/jwt': typeof JwtRoute
  '/jwt-generator': typeof JwtGeneratorRoute
  '/keycode': typeof KeycodeRoute
  '/lorem-ipsum': typeof LoremIpsumRoute
  '/markdown-preview': typeof MarkdownPreviewRoute
  '/markdown-table': typeof MarkdownTableRoute
  '/math-eval': typeof MathEvalRoute
  '/mermaid': typeof MermaidRoute
  '/mime-types': typeof MimeTypesRoute
  '/minify': typeof MinifyRoute
  '/morse-code': typeof MorseCodeRoute
  '/msgpack': typeof MsgpackRoute
  '/number-base': typeof NumberBaseRoute
  '/ogp': typeof OgpRoute
  '/openssl-builder': typeof OpensslBuilderRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/php-serialize': typeof PhpSerializeRoute
  '/pomodoro': typeof PomodoroRoute
  '/port-check': typeof PortCheckRoute
  '/qr-code': typeof QrCodeRoute
  '/random-data': typeof RandomDataRoute
  '/regex-checker': typeof RegexCheckerRoute
  '/robots-txt': typeof RobotsTxtRoute
  '/security-headers': typeof SecurityHeadersRoute
  '/server-env': typeof ServerEnvRoute
  '/slug': typeof SlugRoute
  '/sql': typeof SqlRoute
  '/svg-optimizer': typeof SvgOptimizerRoute
  '/text-case': typeof TextCaseRoute
  '/text-encrypt': typeof TextEncryptRoute
  '/text-replace': typeof TextReplaceRoute
  '/text-sort': typeof TextSortRoute
  '/text-stats': typeof TextStatsRoute
  '/timestamp': typeof TimestampRoute
  '/timezone': typeof TimezoneRoute
  '/toml-json': typeof TomlJsonRoute
  '/top': typeof TopRoute
  '/totp': typeof TotpRoute
  '/transparent-image': typeof TransparentImageRoute
  '/typography-scale': typeof TypographyScaleRoute
  '/unicode': typeof UnicodeRoute
  '/unit-converter': typeof UnitConverterRoute
  '/url-encode': typeof UrlEncodeRoute
  '/url-parser': typeof UrlParserRoute
  '/user-agent': typeof UserAgentRoute
  '/uuid': typeof UuidRoute
  '/video-converter': typeof VideoConverterRoute
  '/whois': typeof WhoisRoute
  '/xml': typeof XmlRoute
  '/yaml-json': typeof YamlJsonRoute
  '/api/image.jpg': typeof ApiImageDotjpgRoute
  '/api/image.png': typeof ApiImageDotpngRoute
  '/api/image.svg': typeof ApiImageDotsvgRoute
  '/api/image.webp': typeof ApiImageDotwebpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ascii-art': typeof AsciiArtRoute
  '/aspect-ratio': typeof AspectRatioRoute
  '/audio-converter': typeof AudioConverterRoute
  '/barcode': typeof BarcodeRoute
  '/base64': typeof Base64Route
  '/base64-image': typeof Base64ImageRoute
  '/bitwise': typeof BitwiseRoute
  '/char-count': typeof CharCountRoute
  '/chmod': typeof ChmodRoute
  '/cidr': typeof CidrRoute
  '/color-blind': typeof ColorBlindRoute
  '/color-contrast': typeof ColorContrastRoute
  '/color-converter': typeof ColorConverterRoute
  '/color-extractor': typeof ColorExtractorRoute
  '/color-harmony': typeof ColorHarmonyRoute
  '/color-palette': typeof ColorPaletteRoute
  '/color-picker': typeof ColorPickerRoute
  '/cookie-parser': typeof CookieParserRoute
  '/cron': typeof CronRoute
  '/cron-parser': typeof CronParserRoute
  '/css-animation': typeof CssAnimationRoute
  '/css-border-radius': typeof CssBorderRadiusRoute
  '/css-box-shadow': typeof CssBoxShadowRoute
  '/css-clip-path': typeof CssClipPathRoute
  '/css-filter': typeof CssFilterRoute
  '/css-flexbox': typeof CssFlexboxRoute
  '/css-gradient': typeof CssGradientRoute
  '/css-grid': typeof CssGridRoute
  '/css-specificity': typeof CssSpecificityRoute
  '/css-text-shadow': typeof CssTextShadowRoute
  '/css-transform': typeof CssTransformRoute
  '/css-unit': typeof CssUnitRoute
  '/csv-json': typeof CsvJsonRoute
  '/curl-builder': typeof CurlBuilderRoute
  '/dice-roll': typeof DiceRollRoute
  '/diff': typeof DiffRoute
  '/discord-emoji': typeof DiscordEmojiRoute
  '/discord-sticker': typeof DiscordStickerRoute
  '/dns-lookup': typeof DnsLookupRoute
  '/dummy-audio': typeof DummyAudioRoute
  '/dummy-image': typeof DummyImageRoute
  '/email-dns': typeof EmailDnsRoute
  '/emoji-converter': typeof EmojiConverterRoute
  '/env-parser': typeof EnvParserRoute
  '/favicon-generator': typeof FaviconGeneratorRoute
  '/gitignore': typeof GitignoreRoute
  '/global-ip': typeof GlobalIpRoute
  '/hash': typeof HashRoute
  '/hex-viewer': typeof HexViewerRoute
  '/html-encode': typeof HtmlEncodeRoute
  '/html-to-jsx': typeof HtmlToJsxRoute
  '/http-client': typeof HttpClientRoute
  '/http-headers': typeof HttpHeadersRoute
  '/http-status': typeof HttpStatusRoute
  '/image-base64': typeof ImageBase64Route
  '/image-compress': typeof ImageCompressRoute
  '/image-crop': typeof ImageCropRoute
  '/image-resize': typeof ImageResizeRoute
  '/image-to-gif': typeof ImageToGifRoute
  '/ip-cidr-check': typeof IpCidrCheckRoute
  '/ip-converter': typeof IpConverterRoute
  '/ip-geolocation': typeof IpGeolocationRoute
  '/json': typeof JsonRoute
  '/json-compare': typeof JsonCompareRoute
  '/json-path': typeof JsonPathRoute
  '/json-schema': typeof JsonSchemaRoute
  '/json-to-ts': typeof JsonToTsRoute
  '/jwt': typeof JwtRoute
  '/jwt-generator': typeof JwtGeneratorRoute
  '/keycode': typeof KeycodeRoute
  '/lorem-ipsum': typeof LoremIpsumRoute
  '/markdown-preview': typeof MarkdownPreviewRoute
  '/markdown-table': typeof MarkdownTableRoute
  '/math-eval': typeof MathEvalRoute
  '/mermaid': typeof MermaidRoute
  '/mime-types': typeof MimeTypesRoute
  '/minify': typeof MinifyRoute
  '/morse-code': typeof MorseCodeRoute
  '/msgpack': typeof MsgpackRoute
  '/number-base': typeof NumberBaseRoute
  '/ogp': typeof OgpRoute
  '/openssl-builder': typeof OpensslBuilderRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/php-serialize': typeof PhpSerializeRoute
  '/pomodoro': typeof PomodoroRoute
  '/port-check': typeof PortCheckRoute
  '/qr-code': typeof QrCodeRoute
  '/random-data': typeof RandomDataRoute
  '/regex-checker': typeof RegexCheckerRoute
  '/robots-txt': typeof RobotsTxtRoute
  '/security-headers': typeof SecurityHeadersRoute
  '/server-env': typeof ServerEnvRoute
  '/slug': typeof SlugRoute
  '/sql': typeof SqlRoute
  '/svg-optimizer': typeof SvgOptimizerRoute
  '/text-case': typeof TextCaseRoute
  '/text-encrypt': typeof TextEncryptRoute
  '/text-replace': typeof TextReplaceRoute
  '/text-sort': typeof TextSortRoute
  '/text-stats': typeof TextStatsRoute
  '/timestamp': typeof TimestampRoute
  '/timezone': typeof TimezoneRoute
  '/toml-json': typeof TomlJsonRoute
  '/top': typeof TopRoute
  '/totp': typeof TotpRoute
  '/transparent-image': typeof TransparentImageRoute
  '/typography-scale': typeof TypographyScaleRoute
  '/unicode': typeof UnicodeRoute
  '/unit-converter': typeof UnitConverterRoute
  '/url-encode': typeof UrlEncodeRoute
  '/url-parser': typeof UrlParserRoute
  '/user-agent': typeof UserAgentRoute
  '/uuid': typeof UuidRoute
  '/video-converter': typeof VideoConverterRoute
  '/whois': typeof WhoisRoute
  '/xml': typeof XmlRoute
  '/yaml-json': typeof YamlJsonRoute
  '/api/image.jpg': typeof ApiImageDotjpgRoute
  '/api/image.png': typeof ApiImageDotpngRoute
  '/api/image.svg': typeof ApiImageDotsvgRoute
  '/api/image.webp': typeof ApiImageDotwebpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ascii-art': typeof AsciiArtRoute
  '/aspect-ratio': typeof AspectRatioRoute
  '/audio-converter': typeof AudioConverterRoute
  '/barcode': typeof BarcodeRoute
  '/base64': typeof Base64Route
  '/base64-image': typeof Base64ImageRoute
  '/bitwise': typeof BitwiseRoute
  '/char-count': typeof CharCountRoute
  '/chmod': typeof ChmodRoute
  '/cidr': typeof CidrRoute
  '/color-blind': typeof ColorBlindRoute
  '/color-contrast': typeof ColorContrastRoute
  '/color-converter': typeof ColorConverterRoute
  '/color-extractor': typeof ColorExtractorRoute
  '/color-harmony': typeof ColorHarmonyRoute
  '/color-palette': typeof ColorPaletteRoute
  '/color-picker': typeof ColorPickerRoute
  '/cookie-parser': typeof CookieParserRoute
  '/cron': typeof CronRoute
  '/cron-parser': typeof CronParserRoute
  '/css-animation': typeof CssAnimationRoute
  '/css-border-radius': typeof CssBorderRadiusRoute
  '/css-box-shadow': typeof CssBoxShadowRoute
  '/css-clip-path': typeof CssClipPathRoute
  '/css-filter': typeof CssFilterRoute
  '/css-flexbox': typeof CssFlexboxRoute
  '/css-gradient': typeof CssGradientRoute
  '/css-grid': typeof CssGridRoute
  '/css-specificity': typeof CssSpecificityRoute
  '/css-text-shadow': typeof CssTextShadowRoute
  '/css-transform': typeof CssTransformRoute
  '/css-unit': typeof CssUnitRoute
  '/csv-json': typeof CsvJsonRoute
  '/curl-builder': typeof CurlBuilderRoute
  '/dice-roll': typeof DiceRollRoute
  '/diff': typeof DiffRoute
  '/discord-emoji': typeof DiscordEmojiRoute
  '/discord-sticker': typeof DiscordStickerRoute
  '/dns-lookup': typeof DnsLookupRoute
  '/dummy-audio': typeof DummyAudioRoute
  '/dummy-image': typeof DummyImageRoute
  '/email-dns': typeof EmailDnsRoute
  '/emoji-converter': typeof EmojiConverterRoute
  '/env-parser': typeof EnvParserRoute
  '/favicon-generator': typeof FaviconGeneratorRoute
  '/gitignore': typeof GitignoreRoute
  '/global-ip': typeof GlobalIpRoute
  '/hash': typeof HashRoute
  '/hex-viewer': typeof HexViewerRoute
  '/html-encode': typeof HtmlEncodeRoute
  '/html-to-jsx': typeof HtmlToJsxRoute
  '/http-client': typeof HttpClientRoute
  '/http-headers': typeof HttpHeadersRoute
  '/http-status': typeof HttpStatusRoute
  '/image-base64': typeof ImageBase64Route
  '/image-compress': typeof ImageCompressRoute
  '/image-crop': typeof ImageCropRoute
  '/image-resize': typeof ImageResizeRoute
  '/image-to-gif': typeof ImageToGifRoute
  '/ip-cidr-check': typeof IpCidrCheckRoute
  '/ip-converter': typeof IpConverterRoute
  '/ip-geolocation': typeof IpGeolocationRoute
  '/json': typeof JsonRoute
  '/json-compare': typeof JsonCompareRoute
  '/json-path': typeof JsonPathRoute
  '/json-schema': typeof JsonSchemaRoute
  '/json-to-ts': typeof JsonToTsRoute
  '/jwt': typeof JwtRoute
  '/jwt-generator': typeof JwtGeneratorRoute
  '/keycode': typeof KeycodeRoute
  '/lorem-ipsum': typeof LoremIpsumRoute
  '/markdown-preview': typeof MarkdownPreviewRoute
  '/markdown-table': typeof MarkdownTableRoute
  '/math-eval': typeof MathEvalRoute
  '/mermaid': typeof MermaidRoute
  '/mime-types': typeof MimeTypesRoute
  '/minify': typeof MinifyRoute
  '/morse-code': typeof MorseCodeRoute
  '/msgpack': typeof MsgpackRoute
  '/number-base': typeof NumberBaseRoute
  '/ogp': typeof OgpRoute
  '/openssl-builder': typeof OpensslBuilderRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/php-serialize': typeof PhpSerializeRoute
  '/pomodoro': typeof PomodoroRoute
  '/port-check': typeof PortCheckRoute
  '/qr-code': typeof QrCodeRoute
  '/random-data': typeof RandomDataRoute
  '/regex-checker': typeof RegexCheckerRoute
  '/robots-txt': typeof RobotsTxtRoute
  '/security-headers': typeof SecurityHeadersRoute
  '/server-env': typeof ServerEnvRoute
  '/slug': typeof SlugRoute
  '/sql': typeof SqlRoute
  '/svg-optimizer': typeof SvgOptimizerRoute
  '/text-case': typeof TextCaseRoute
  '/text-encrypt': typeof TextEncryptRoute
  '/text-replace': typeof TextReplaceRoute
  '/text-sort': typeof TextSortRoute
  '/text-stats': typeof TextStatsRoute
  '/timestamp': typeof TimestampRoute
  '/timezone': typeof TimezoneRoute
  '/toml-json': typeof TomlJsonRoute
  '/top': typeof TopRoute
  '/totp': typeof TotpRoute
  '/transparent-image': typeof TransparentImageRoute
  '/typography-scale': typeof TypographyScaleRoute
  '/unicode': typeof UnicodeRoute
  '/unit-converter': typeof UnitConverterRoute
  '/url-encode': typeof UrlEncodeRoute
  '/url-parser': typeof UrlParserRoute
  '/user-agent': typeof UserAgentRoute
  '/uuid': typeof UuidRoute
  '/video-converter': typeof VideoConverterRoute
  '/whois': typeof WhoisRoute
  '/xml': typeof XmlRoute
  '/yaml-json': typeof YamlJsonRoute
  '/api/image.jpg': typeof ApiImageDotjpgRoute
  '/api/image.png': typeof ApiImageDotpngRoute
  '/api/image.svg': typeof ApiImageDotsvgRoute
  '/api/image.webp': typeof ApiImageDotwebpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ascii-art'
    | '/aspect-ratio'
    | '/audio-converter'
    | '/barcode'
    | '/base64'
    | '/base64-image'
    | '/bitwise'
    | '/char-count'
    | '/chmod'
    | '/cidr'
    | '/color-blind'
    | '/color-contrast'
    | '/color-converter'
    | '/color-extractor'
    | '/color-harmony'
    | '/color-palette'
    | '/color-picker'
    | '/cookie-parser'
    | '/cron'
    | '/cron-parser'
    | '/css-animation'
    | '/css-border-radius'
    | '/css-box-shadow'
    | '/css-clip-path'
    | '/css-filter'
    | '/css-flexbox'
    | '/css-gradient'
    | '/css-grid'
    | '/css-specificity'
    | '/css-text-shadow'
    | '/css-transform'
    | '/css-unit'
    | '/csv-json'
    | '/curl-builder'
    | '/dice-roll'
    | '/diff'
    | '/discord-emoji'
    | '/discord-sticker'
    | '/dns-lookup'
    | '/dummy-audio'
    | '/dummy-image'
    | '/email-dns'
    | '/emoji-converter'
    | '/env-parser'
    | '/favicon-generator'
    | '/gitignore'
    | '/global-ip'
    | '/hash'
    | '/hex-viewer'
    | '/html-encode'
    | '/html-to-jsx'
    | '/http-client'
    | '/http-headers'
    | '/http-status'
    | '/image-base64'
    | '/image-compress'
    | '/image-crop'
    | '/image-resize'
    | '/image-to-gif'
    | '/ip-cidr-check'
    | '/ip-converter'
    | '/ip-geolocation'
    | '/json'
    | '/json-compare'
    | '/json-path'
    | '/json-schema'
    | '/json-to-ts'
    | '/jwt'
    | '/jwt-generator'
    | '/keycode'
    | '/lorem-ipsum'
    | '/markdown-preview'
    | '/markdown-table'
    | '/math-eval'
    | '/mermaid'
    | '/mime-types'
    | '/minify'
    | '/morse-code'
    | '/msgpack'
    | '/number-base'
    | '/ogp'
    | '/openssl-builder'
    | '/password-generator'
    | '/php-serialize'
    | '/pomodoro'
    | '/port-check'
    | '/qr-code'
    | '/random-data'
    | '/regex-checker'
    | '/robots-txt'
    | '/security-headers'
    | '/server-env'
    | '/slug'
    | '/sql'
    | '/svg-optimizer'
    | '/text-case'
    | '/text-encrypt'
    | '/text-replace'
    | '/text-sort'
    | '/text-stats'
    | '/timestamp'
    | '/timezone'
    | '/toml-json'
    | '/top'
    | '/totp'
    | '/transparent-image'
    | '/typography-scale'
    | '/unicode'
    | '/unit-converter'
    | '/url-encode'
    | '/url-parser'
    | '/user-agent'
    | '/uuid'
    | '/video-converter'
    | '/whois'
    | '/xml'
    | '/yaml-json'
    | '/api/image.jpg'
    | '/api/image.png'
    | '/api/image.svg'
    | '/api/image.webp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ascii-art'
    | '/aspect-ratio'
    | '/audio-converter'
    | '/barcode'
    | '/base64'
    | '/base64-image'
    | '/bitwise'
    | '/char-count'
    | '/chmod'
    | '/cidr'
    | '/color-blind'
    | '/color-contrast'
    | '/color-converter'
    | '/color-extractor'
    | '/color-harmony'
    | '/color-palette'
    | '/color-picker'
    | '/cookie-parser'
    | '/cron'
    | '/cron-parser'
    | '/css-animation'
    | '/css-border-radius'
    | '/css-box-shadow'
    | '/css-clip-path'
    | '/css-filter'
    | '/css-flexbox'
    | '/css-gradient'
    | '/css-grid'
    | '/css-specificity'
    | '/css-text-shadow'
    | '/css-transform'
    | '/css-unit'
    | '/csv-json'
    | '/curl-builder'
    | '/dice-roll'
    | '/diff'
    | '/discord-emoji'
    | '/discord-sticker'
    | '/dns-lookup'
    | '/dummy-audio'
    | '/dummy-image'
    | '/email-dns'
    | '/emoji-converter'
    | '/env-parser'
    | '/favicon-generator'
    | '/gitignore'
    | '/global-ip'
    | '/hash'
    | '/hex-viewer'
    | '/html-encode'
    | '/html-to-jsx'
    | '/http-client'
    | '/http-headers'
    | '/http-status'
    | '/image-base64'
    | '/image-compress'
    | '/image-crop'
    | '/image-resize'
    | '/image-to-gif'
    | '/ip-cidr-check'
    | '/ip-converter'
    | '/ip-geolocation'
    | '/json'
    | '/json-compare'
    | '/json-path'
    | '/json-schema'
    | '/json-to-ts'
    | '/jwt'
    | '/jwt-generator'
    | '/keycode'
    | '/lorem-ipsum'
    | '/markdown-preview'
    | '/markdown-table'
    | '/math-eval'
    | '/mermaid'
    | '/mime-types'
    | '/minify'
    | '/morse-code'
    | '/msgpack'
    | '/number-base'
    | '/ogp'
    | '/openssl-builder'
    | '/password-generator'
    | '/php-serialize'
    | '/pomodoro'
    | '/port-check'
    | '/qr-code'
    | '/random-data'
    | '/regex-checker'
    | '/robots-txt'
    | '/security-headers'
    | '/server-env'
    | '/slug'
    | '/sql'
    | '/svg-optimizer'
    | '/text-case'
    | '/text-encrypt'
    | '/text-replace'
    | '/text-sort'
    | '/text-stats'
    | '/timestamp'
    | '/timezone'
    | '/toml-json'
    | '/top'
    | '/totp'
    | '/transparent-image'
    | '/typography-scale'
    | '/unicode'
    | '/unit-converter'
    | '/url-encode'
    | '/url-parser'
    | '/user-agent'
    | '/uuid'
    | '/video-converter'
    | '/whois'
    | '/xml'
    | '/yaml-json'
    | '/api/image.jpg'
    | '/api/image.png'
    | '/api/image.svg'
    | '/api/image.webp'
  id:
    | '__root__'
    | '/'
    | '/ascii-art'
    | '/aspect-ratio'
    | '/audio-converter'
    | '/barcode'
    | '/base64'
    | '/base64-image'
    | '/bitwise'
    | '/char-count'
    | '/chmod'
    | '/cidr'
    | '/color-blind'
    | '/color-contrast'
    | '/color-converter'
    | '/color-extractor'
    | '/color-harmony'
    | '/color-palette'
    | '/color-picker'
    | '/cookie-parser'
    | '/cron'
    | '/cron-parser'
    | '/css-animation'
    | '/css-border-radius'
    | '/css-box-shadow'
    | '/css-clip-path'
    | '/css-filter'
    | '/css-flexbox'
    | '/css-gradient'
    | '/css-grid'
    | '/css-specificity'
    | '/css-text-shadow'
    | '/css-transform'
    | '/css-unit'
    | '/csv-json'
    | '/curl-builder'
    | '/dice-roll'
    | '/diff'
    | '/discord-emoji'
    | '/discord-sticker'
    | '/dns-lookup'
    | '/dummy-audio'
    | '/dummy-image'
    | '/email-dns'
    | '/emoji-converter'
    | '/env-parser'
    | '/favicon-generator'
    | '/gitignore'
    | '/global-ip'
    | '/hash'
    | '/hex-viewer'
    | '/html-encode'
    | '/html-to-jsx'
    | '/http-client'
    | '/http-headers'
    | '/http-status'
    | '/image-base64'
    | '/image-compress'
    | '/image-crop'
    | '/image-resize'
    | '/image-to-gif'
    | '/ip-cidr-check'
    | '/ip-converter'
    | '/ip-geolocation'
    | '/json'
    | '/json-compare'
    | '/json-path'
    | '/json-schema'
    | '/json-to-ts'
    | '/jwt'
    | '/jwt-generator'
    | '/keycode'
    | '/lorem-ipsum'
    | '/markdown-preview'
    | '/markdown-table'
    | '/math-eval'
    | '/mermaid'
    | '/mime-types'
    | '/minify'
    | '/morse-code'
    | '/msgpack'
    | '/number-base'
    | '/ogp'
    | '/openssl-builder'
    | '/password-generator'
    | '/php-serialize'
    | '/pomodoro'
    | '/port-check'
    | '/qr-code'
    | '/random-data'
    | '/regex-checker'
    | '/robots-txt'
    | '/security-headers'
    | '/server-env'
    | '/slug'
    | '/sql'
    | '/svg-optimizer'
    | '/text-case'
    | '/text-encrypt'
    | '/text-replace'
    | '/text-sort'
    | '/text-stats'
    | '/timestamp'
    | '/timezone'
    | '/toml-json'
    | '/top'
    | '/totp'
    | '/transparent-image'
    | '/typography-scale'
    | '/unicode'
    | '/unit-converter'
    | '/url-encode'
    | '/url-parser'
    | '/user-agent'
    | '/uuid'
    | '/video-converter'
    | '/whois'
    | '/xml'
    | '/yaml-json'
    | '/api/image.jpg'
    | '/api/image.png'
    | '/api/image.svg'
    | '/api/image.webp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsciiArtRoute: typeof AsciiArtRoute
  AspectRatioRoute: typeof AspectRatioRoute
  AudioConverterRoute: typeof AudioConverterRoute
  BarcodeRoute: typeof BarcodeRoute
  Base64Route: typeof Base64Route
  Base64ImageRoute: typeof Base64ImageRoute
  BitwiseRoute: typeof BitwiseRoute
  CharCountRoute: typeof CharCountRoute
  ChmodRoute: typeof ChmodRoute
  CidrRoute: typeof CidrRoute
  ColorBlindRoute: typeof ColorBlindRoute
  ColorContrastRoute: typeof ColorContrastRoute
  ColorConverterRoute: typeof ColorConverterRoute
  ColorExtractorRoute: typeof ColorExtractorRoute
  ColorHarmonyRoute: typeof ColorHarmonyRoute
  ColorPaletteRoute: typeof ColorPaletteRoute
  ColorPickerRoute: typeof ColorPickerRoute
  CookieParserRoute: typeof CookieParserRoute
  CronRoute: typeof CronRoute
  CronParserRoute: typeof CronParserRoute
  CssAnimationRoute: typeof CssAnimationRoute
  CssBorderRadiusRoute: typeof CssBorderRadiusRoute
  CssBoxShadowRoute: typeof CssBoxShadowRoute
  CssClipPathRoute: typeof CssClipPathRoute
  CssFilterRoute: typeof CssFilterRoute
  CssFlexboxRoute: typeof CssFlexboxRoute
  CssGradientRoute: typeof CssGradientRoute
  CssGridRoute: typeof CssGridRoute
  CssSpecificityRoute: typeof CssSpecificityRoute
  CssTextShadowRoute: typeof CssTextShadowRoute
  CssTransformRoute: typeof CssTransformRoute
  CssUnitRoute: typeof CssUnitRoute
  CsvJsonRoute: typeof CsvJsonRoute
  CurlBuilderRoute: typeof CurlBuilderRoute
  DiceRollRoute: typeof DiceRollRoute
  DiffRoute: typeof DiffRoute
  DiscordEmojiRoute: typeof DiscordEmojiRoute
  DiscordStickerRoute: typeof DiscordStickerRoute
  DnsLookupRoute: typeof DnsLookupRoute
  DummyAudioRoute: typeof DummyAudioRoute
  DummyImageRoute: typeof DummyImageRoute
  EmailDnsRoute: typeof EmailDnsRoute
  EmojiConverterRoute: typeof EmojiConverterRoute
  EnvParserRoute: typeof EnvParserRoute
  FaviconGeneratorRoute: typeof FaviconGeneratorRoute
  GitignoreRoute: typeof GitignoreRoute
  GlobalIpRoute: typeof GlobalIpRoute
  HashRoute: typeof HashRoute
  HexViewerRoute: typeof HexViewerRoute
  HtmlEncodeRoute: typeof HtmlEncodeRoute
  HtmlToJsxRoute: typeof HtmlToJsxRoute
  HttpClientRoute: typeof HttpClientRoute
  HttpHeadersRoute: typeof HttpHeadersRoute
  HttpStatusRoute: typeof HttpStatusRoute
  ImageBase64Route: typeof ImageBase64Route
  ImageCompressRoute: typeof ImageCompressRoute
  ImageCropRoute: typeof ImageCropRoute
  ImageResizeRoute: typeof ImageResizeRoute
  ImageToGifRoute: typeof ImageToGifRoute
  IpCidrCheckRoute: typeof IpCidrCheckRoute
  IpConverterRoute: typeof IpConverterRoute
  IpGeolocationRoute: typeof IpGeolocationRoute
  JsonRoute: typeof JsonRoute
  JsonCompareRoute: typeof JsonCompareRoute
  JsonPathRoute: typeof JsonPathRoute
  JsonSchemaRoute: typeof JsonSchemaRoute
  JsonToTsRoute: typeof JsonToTsRoute
  JwtRoute: typeof JwtRoute
  JwtGeneratorRoute: typeof JwtGeneratorRoute
  KeycodeRoute: typeof KeycodeRoute
  LoremIpsumRoute: typeof LoremIpsumRoute
  MarkdownPreviewRoute: typeof MarkdownPreviewRoute
  MarkdownTableRoute: typeof MarkdownTableRoute
  MathEvalRoute: typeof MathEvalRoute
  MermaidRoute: typeof MermaidRoute
  MimeTypesRoute: typeof MimeTypesRoute
  MinifyRoute: typeof MinifyRoute
  MorseCodeRoute: typeof MorseCodeRoute
  MsgpackRoute: typeof MsgpackRoute
  NumberBaseRoute: typeof NumberBaseRoute
  OgpRoute: typeof OgpRoute
  OpensslBuilderRoute: typeof OpensslBuilderRoute
  PasswordGeneratorRoute: typeof PasswordGeneratorRoute
  PhpSerializeRoute: typeof PhpSerializeRoute
  PomodoroRoute: typeof PomodoroRoute
  PortCheckRoute: typeof PortCheckRoute
  QrCodeRoute: typeof QrCodeRoute
  RandomDataRoute: typeof RandomDataRoute
  RegexCheckerRoute: typeof RegexCheckerRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SecurityHeadersRoute: typeof SecurityHeadersRoute
  ServerEnvRoute: typeof ServerEnvRoute
  SlugRoute: typeof SlugRoute
  SqlRoute: typeof SqlRoute
  SvgOptimizerRoute: typeof SvgOptimizerRoute
  TextCaseRoute: typeof TextCaseRoute
  TextEncryptRoute: typeof TextEncryptRoute
  TextReplaceRoute: typeof TextReplaceRoute
  TextSortRoute: typeof TextSortRoute
  TextStatsRoute: typeof TextStatsRoute
  TimestampRoute: typeof TimestampRoute
  TimezoneRoute: typeof TimezoneRoute
  TomlJsonRoute: typeof TomlJsonRoute
  TopRoute: typeof TopRoute
  TotpRoute: typeof TotpRoute
  TransparentImageRoute: typeof TransparentImageRoute
  TypographyScaleRoute: typeof TypographyScaleRoute
  UnicodeRoute: typeof UnicodeRoute
  UnitConverterRoute: typeof UnitConverterRoute
  UrlEncodeRoute: typeof UrlEncodeRoute
  UrlParserRoute: typeof UrlParserRoute
  UserAgentRoute: typeof UserAgentRoute
  UuidRoute: typeof UuidRoute
  VideoConverterRoute: typeof VideoConverterRoute
  WhoisRoute: typeof WhoisRoute
  XmlRoute: typeof XmlRoute
  YamlJsonRoute: typeof YamlJsonRoute
  ApiImageDotjpgRoute: typeof ApiImageDotjpgRoute
  ApiImageDotpngRoute: typeof ApiImageDotpngRoute
  ApiImageDotsvgRoute: typeof ApiImageDotsvgRoute
  ApiImageDotwebpRoute: typeof ApiImageDotwebpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yaml-json': {
      id: '/yaml-json'
      path: '/yaml-json'
      fullPath: '/yaml-json'
      preLoaderRoute: typeof YamlJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xml': {
      id: '/xml'
      path: '/xml'
      fullPath: '/xml'
      preLoaderRoute: typeof XmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whois': {
      id: '/whois'
      path: '/whois'
      fullPath: '/whois'
      preLoaderRoute: typeof WhoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-converter': {
      id: '/video-converter'
      path: '/video-converter'
      fullPath: '/video-converter'
      preLoaderRoute: typeof VideoConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uuid': {
      id: '/uuid'
      path: '/uuid'
      fullPath: '/uuid'
      preLoaderRoute: typeof UuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-agent': {
      id: '/user-agent'
      path: '/user-agent'
      fullPath: '/user-agent'
      preLoaderRoute: typeof UserAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url-parser': {
      id: '/url-parser'
      path: '/url-parser'
      fullPath: '/url-parser'
      preLoaderRoute: typeof UrlParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url-encode': {
      id: '/url-encode'
      path: '/url-encode'
      fullPath: '/url-encode'
      preLoaderRoute: typeof UrlEncodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit-converter': {
      id: '/unit-converter'
      path: '/unit-converter'
      fullPath: '/unit-converter'
      preLoaderRoute: typeof UnitConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unicode': {
      id: '/unicode'
      path: '/unicode'
      fullPath: '/unicode'
      preLoaderRoute: typeof UnicodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typography-scale': {
      id: '/typography-scale'
      path: '/typography-scale'
      fullPath: '/typography-scale'
      preLoaderRoute: typeof TypographyScaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparent-image': {
      id: '/transparent-image'
      path: '/transparent-image'
      fullPath: '/transparent-image'
      preLoaderRoute: typeof TransparentImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totp': {
      id: '/totp'
      path: '/totp'
      fullPath: '/totp'
      preLoaderRoute: typeof TotpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top': {
      id: '/top'
      path: '/top'
      fullPath: '/top'
      preLoaderRoute: typeof TopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toml-json': {
      id: '/toml-json'
      path: '/toml-json'
      fullPath: '/toml-json'
      preLoaderRoute: typeof TomlJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timezone': {
      id: '/timezone'
      path: '/timezone'
      fullPath: '/timezone'
      preLoaderRoute: typeof TimezoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timestamp': {
      id: '/timestamp'
      path: '/timestamp'
      fullPath: '/timestamp'
      preLoaderRoute: typeof TimestampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-stats': {
      id: '/text-stats'
      path: '/text-stats'
      fullPath: '/text-stats'
      preLoaderRoute: typeof TextStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-sort': {
      id: '/text-sort'
      path: '/text-sort'
      fullPath: '/text-sort'
      preLoaderRoute: typeof TextSortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-replace': {
      id: '/text-replace'
      path: '/text-replace'
      fullPath: '/text-replace'
      preLoaderRoute: typeof TextReplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-encrypt': {
      id: '/text-encrypt'
      path: '/text-encrypt'
      fullPath: '/text-encrypt'
      preLoaderRoute: typeof TextEncryptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-case': {
      id: '/text-case'
      path: '/text-case'
      fullPath: '/text-case'
      preLoaderRoute: typeof TextCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/svg-optimizer': {
      id: '/svg-optimizer'
      path: '/svg-optimizer'
      fullPath: '/svg-optimizer'
      preLoaderRoute: typeof SvgOptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slug': {
      id: '/slug'
      path: '/slug'
      fullPath: '/slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-env': {
      id: '/server-env'
      path: '/server-env'
      fullPath: '/server-env'
      preLoaderRoute: typeof ServerEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-headers': {
      id: '/security-headers'
      path: '/security-headers'
      fullPath: '/security-headers'
      preLoaderRoute: typeof SecurityHeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots-txt': {
      id: '/robots-txt'
      path: '/robots-txt'
      fullPath: '/robots-txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regex-checker': {
      id: '/regex-checker'
      path: '/regex-checker'
      fullPath: '/regex-checker'
      preLoaderRoute: typeof RegexCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-data': {
      id: '/random-data'
      path: '/random-data'
      fullPath: '/random-data'
      preLoaderRoute: typeof RandomDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code': {
      id: '/qr-code'
      path: '/qr-code'
      fullPath: '/qr-code'
      preLoaderRoute: typeof QrCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/port-check': {
      id: '/port-check'
      path: '/port-check'
      fullPath: '/port-check'
      preLoaderRoute: typeof PortCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pomodoro': {
      id: '/pomodoro'
      path: '/pomodoro'
      fullPath: '/pomodoro'
      preLoaderRoute: typeof PomodoroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/php-serialize': {
      id: '/php-serialize'
      path: '/php-serialize'
      fullPath: '/php-serialize'
      preLoaderRoute: typeof PhpSerializeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-generator': {
      id: '/password-generator'
      path: '/password-generator'
      fullPath: '/password-generator'
      preLoaderRoute: typeof PasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openssl-builder': {
      id: '/openssl-builder'
      path: '/openssl-builder'
      fullPath: '/openssl-builder'
      preLoaderRoute: typeof OpensslBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ogp': {
      id: '/ogp'
      path: '/ogp'
      fullPath: '/ogp'
      preLoaderRoute: typeof OgpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/number-base': {
      id: '/number-base'
      path: '/number-base'
      fullPath: '/number-base'
      preLoaderRoute: typeof NumberBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/msgpack': {
      id: '/msgpack'
      path: '/msgpack'
      fullPath: '/msgpack'
      preLoaderRoute: typeof MsgpackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/morse-code': {
      id: '/morse-code'
      path: '/morse-code'
      fullPath: '/morse-code'
      preLoaderRoute: typeof MorseCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minify': {
      id: '/minify'
      path: '/minify'
      fullPath: '/minify'
      preLoaderRoute: typeof MinifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mime-types': {
      id: '/mime-types'
      path: '/mime-types'
      fullPath: '/mime-types'
      preLoaderRoute: typeof MimeTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mermaid': {
      id: '/mermaid'
      path: '/mermaid'
      fullPath: '/mermaid'
      preLoaderRoute: typeof MermaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math-eval': {
      id: '/math-eval'
      path: '/math-eval'
      fullPath: '/math-eval'
      preLoaderRoute: typeof MathEvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markdown-table': {
      id: '/markdown-table'
      path: '/markdown-table'
      fullPath: '/markdown-table'
      preLoaderRoute: typeof MarkdownTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markdown-preview': {
      id: '/markdown-preview'
      path: '/markdown-preview'
      fullPath: '/markdown-preview'
      preLoaderRoute: typeof MarkdownPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lorem-ipsum': {
      id: '/lorem-ipsum'
      path: '/lorem-ipsum'
      fullPath: '/lorem-ipsum'
      preLoaderRoute: typeof LoremIpsumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keycode': {
      id: '/keycode'
      path: '/keycode'
      fullPath: '/keycode'
      preLoaderRoute: typeof KeycodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwt-generator': {
      id: '/jwt-generator'
      path: '/jwt-generator'
      fullPath: '/jwt-generator'
      preLoaderRoute: typeof JwtGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwt': {
      id: '/jwt'
      path: '/jwt'
      fullPath: '/jwt'
      preLoaderRoute: typeof JwtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-ts': {
      id: '/json-to-ts'
      path: '/json-to-ts'
      fullPath: '/json-to-ts'
      preLoaderRoute: typeof JsonToTsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-schema': {
      id: '/json-schema'
      path: '/json-schema'
      fullPath: '/json-schema'
      preLoaderRoute: typeof JsonSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-path': {
      id: '/json-path'
      path: '/json-path'
      fullPath: '/json-path'
      preLoaderRoute: typeof JsonPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-compare': {
      id: '/json-compare'
      path: '/json-compare'
      fullPath: '/json-compare'
      preLoaderRoute: typeof JsonCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json': {
      id: '/json'
      path: '/json'
      fullPath: '/json'
      preLoaderRoute: typeof JsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-geolocation': {
      id: '/ip-geolocation'
      path: '/ip-geolocation'
      fullPath: '/ip-geolocation'
      preLoaderRoute: typeof IpGeolocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-converter': {
      id: '/ip-converter'
      path: '/ip-converter'
      fullPath: '/ip-converter'
      preLoaderRoute: typeof IpConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-cidr-check': {
      id: '/ip-cidr-check'
      path: '/ip-cidr-check'
      fullPath: '/ip-cidr-check'
      preLoaderRoute: typeof IpCidrCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-gif': {
      id: '/image-to-gif'
      path: '/image-to-gif'
      fullPath: '/image-to-gif'
      preLoaderRoute: typeof ImageToGifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-resize': {
      id: '/image-resize'
      path: '/image-resize'
      fullPath: '/image-resize'
      preLoaderRoute: typeof ImageResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-crop': {
      id: '/image-crop'
      path: '/image-crop'
      fullPath: '/image-crop'
      preLoaderRoute: typeof ImageCropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-compress': {
      id: '/image-compress'
      path: '/image-compress'
      fullPath: '/image-compress'
      preLoaderRoute: typeof ImageCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-base64': {
      id: '/image-base64'
      path: '/image-base64'
      fullPath: '/image-base64'
      preLoaderRoute: typeof ImageBase64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http-status': {
      id: '/http-status'
      path: '/http-status'
      fullPath: '/http-status'
      preLoaderRoute: typeof HttpStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http-headers': {
      id: '/http-headers'
      path: '/http-headers'
      fullPath: '/http-headers'
      preLoaderRoute: typeof HttpHeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http-client': {
      id: '/http-client'
      path: '/http-client'
      fullPath: '/http-client'
      preLoaderRoute: typeof HttpClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html-to-jsx': {
      id: '/html-to-jsx'
      path: '/html-to-jsx'
      fullPath: '/html-to-jsx'
      preLoaderRoute: typeof HtmlToJsxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html-encode': {
      id: '/html-encode'
      path: '/html-encode'
      fullPath: '/html-encode'
      preLoaderRoute: typeof HtmlEncodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hex-viewer': {
      id: '/hex-viewer'
      path: '/hex-viewer'
      fullPath: '/hex-viewer'
      preLoaderRoute: typeof HexViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash': {
      id: '/hash'
      path: '/hash'
      fullPath: '/hash'
      preLoaderRoute: typeof HashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-ip': {
      id: '/global-ip'
      path: '/global-ip'
      fullPath: '/global-ip'
      preLoaderRoute: typeof GlobalIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gitignore': {
      id: '/gitignore'
      path: '/gitignore'
      fullPath: '/gitignore'
      preLoaderRoute: typeof GitignoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon-generator': {
      id: '/favicon-generator'
      path: '/favicon-generator'
      fullPath: '/favicon-generator'
      preLoaderRoute: typeof FaviconGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/env-parser': {
      id: '/env-parser'
      path: '/env-parser'
      fullPath: '/env-parser'
      preLoaderRoute: typeof EnvParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emoji-converter': {
      id: '/emoji-converter'
      path: '/emoji-converter'
      fullPath: '/emoji-converter'
      preLoaderRoute: typeof EmojiConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-dns': {
      id: '/email-dns'
      path: '/email-dns'
      fullPath: '/email-dns'
      preLoaderRoute: typeof EmailDnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dummy-image': {
      id: '/dummy-image'
      path: '/dummy-image'
      fullPath: '/dummy-image'
      preLoaderRoute: typeof DummyImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dummy-audio': {
      id: '/dummy-audio'
      path: '/dummy-audio'
      fullPath: '/dummy-audio'
      preLoaderRoute: typeof DummyAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns-lookup': {
      id: '/dns-lookup'
      path: '/dns-lookup'
      fullPath: '/dns-lookup'
      preLoaderRoute: typeof DnsLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord-sticker': {
      id: '/discord-sticker'
      path: '/discord-sticker'
      fullPath: '/discord-sticker'
      preLoaderRoute: typeof DiscordStickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord-emoji': {
      id: '/discord-emoji'
      path: '/discord-emoji'
      fullPath: '/discord-emoji'
      preLoaderRoute: typeof DiscordEmojiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff': {
      id: '/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof DiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dice-roll': {
      id: '/dice-roll'
      path: '/dice-roll'
      fullPath: '/dice-roll'
      preLoaderRoute: typeof DiceRollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curl-builder': {
      id: '/curl-builder'
      path: '/curl-builder'
      fullPath: '/curl-builder'
      preLoaderRoute: typeof CurlBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv-json': {
      id: '/csv-json'
      path: '/csv-json'
      fullPath: '/csv-json'
      preLoaderRoute: typeof CsvJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-unit': {
      id: '/css-unit'
      path: '/css-unit'
      fullPath: '/css-unit'
      preLoaderRoute: typeof CssUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-transform': {
      id: '/css-transform'
      path: '/css-transform'
      fullPath: '/css-transform'
      preLoaderRoute: typeof CssTransformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-text-shadow': {
      id: '/css-text-shadow'
      path: '/css-text-shadow'
      fullPath: '/css-text-shadow'
      preLoaderRoute: typeof CssTextShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-specificity': {
      id: '/css-specificity'
      path: '/css-specificity'
      fullPath: '/css-specificity'
      preLoaderRoute: typeof CssSpecificityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-grid': {
      id: '/css-grid'
      path: '/css-grid'
      fullPath: '/css-grid'
      preLoaderRoute: typeof CssGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-gradient': {
      id: '/css-gradient'
      path: '/css-gradient'
      fullPath: '/css-gradient'
      preLoaderRoute: typeof CssGradientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-flexbox': {
      id: '/css-flexbox'
      path: '/css-flexbox'
      fullPath: '/css-flexbox'
      preLoaderRoute: typeof CssFlexboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-filter': {
      id: '/css-filter'
      path: '/css-filter'
      fullPath: '/css-filter'
      preLoaderRoute: typeof CssFilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-clip-path': {
      id: '/css-clip-path'
      path: '/css-clip-path'
      fullPath: '/css-clip-path'
      preLoaderRoute: typeof CssClipPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-box-shadow': {
      id: '/css-box-shadow'
      path: '/css-box-shadow'
      fullPath: '/css-box-shadow'
      preLoaderRoute: typeof CssBoxShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-border-radius': {
      id: '/css-border-radius'
      path: '/css-border-radius'
      fullPath: '/css-border-radius'
      preLoaderRoute: typeof CssBorderRadiusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-animation': {
      id: '/css-animation'
      path: '/css-animation'
      fullPath: '/css-animation'
      preLoaderRoute: typeof CssAnimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron-parser': {
      id: '/cron-parser'
      path: '/cron-parser'
      fullPath: '/cron-parser'
      preLoaderRoute: typeof CronParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-parser': {
      id: '/cookie-parser'
      path: '/cookie-parser'
      fullPath: '/cookie-parser'
      preLoaderRoute: typeof CookieParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-picker': {
      id: '/color-picker'
      path: '/color-picker'
      fullPath: '/color-picker'
      preLoaderRoute: typeof ColorPickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-palette': {
      id: '/color-palette'
      path: '/color-palette'
      fullPath: '/color-palette'
      preLoaderRoute: typeof ColorPaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-harmony': {
      id: '/color-harmony'
      path: '/color-harmony'
      fullPath: '/color-harmony'
      preLoaderRoute: typeof ColorHarmonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-extractor': {
      id: '/color-extractor'
      path: '/color-extractor'
      fullPath: '/color-extractor'
      preLoaderRoute: typeof ColorExtractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-converter': {
      id: '/color-converter'
      path: '/color-converter'
      fullPath: '/color-converter'
      preLoaderRoute: typeof ColorConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-contrast': {
      id: '/color-contrast'
      path: '/color-contrast'
      fullPath: '/color-contrast'
      preLoaderRoute: typeof ColorContrastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-blind': {
      id: '/color-blind'
      path: '/color-blind'
      fullPath: '/color-blind'
      preLoaderRoute: typeof ColorBlindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidr': {
      id: '/cidr'
      path: '/cidr'
      fullPath: '/cidr'
      preLoaderRoute: typeof CidrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chmod': {
      id: '/chmod'
      path: '/chmod'
      fullPath: '/chmod'
      preLoaderRoute: typeof ChmodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/char-count': {
      id: '/char-count'
      path: '/char-count'
      fullPath: '/char-count'
      preLoaderRoute: typeof CharCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitwise': {
      id: '/bitwise'
      path: '/bitwise'
      fullPath: '/bitwise'
      preLoaderRoute: typeof BitwiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base64-image': {
      id: '/base64-image'
      path: '/base64-image'
      fullPath: '/base64-image'
      preLoaderRoute: typeof Base64ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base64': {
      id: '/base64'
      path: '/base64'
      fullPath: '/base64'
      preLoaderRoute: typeof Base64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barcode': {
      id: '/barcode'
      path: '/barcode'
      fullPath: '/barcode'
      preLoaderRoute: typeof BarcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-converter': {
      id: '/audio-converter'
      path: '/audio-converter'
      fullPath: '/audio-converter'
      preLoaderRoute: typeof AudioConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aspect-ratio': {
      id: '/aspect-ratio'
      path: '/aspect-ratio'
      fullPath: '/aspect-ratio'
      preLoaderRoute: typeof AspectRatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascii-art': {
      id: '/ascii-art'
      path: '/ascii-art'
      fullPath: '/ascii-art'
      preLoaderRoute: typeof AsciiArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image.webp': {
      id: '/api/image.webp'
      path: '/api/image.webp'
      fullPath: '/api/image.webp'
      preLoaderRoute: typeof ApiImageDotwebpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image.svg': {
      id: '/api/image.svg'
      path: '/api/image.svg'
      fullPath: '/api/image.svg'
      preLoaderRoute: typeof ApiImageDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image.png': {
      id: '/api/image.png'
      path: '/api/image.png'
      fullPath: '/api/image.png'
      preLoaderRoute: typeof ApiImageDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image.jpg': {
      id: '/api/image.jpg'
      path: '/api/image.jpg'
      fullPath: '/api/image.jpg'
      preLoaderRoute: typeof ApiImageDotjpgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsciiArtRoute: AsciiArtRoute,
  AspectRatioRoute: AspectRatioRoute,
  AudioConverterRoute: AudioConverterRoute,
  BarcodeRoute: BarcodeRoute,
  Base64Route: Base64Route,
  Base64ImageRoute: Base64ImageRoute,
  BitwiseRoute: BitwiseRoute,
  CharCountRoute: CharCountRoute,
  ChmodRoute: ChmodRoute,
  CidrRoute: CidrRoute,
  ColorBlindRoute: ColorBlindRoute,
  ColorContrastRoute: ColorContrastRoute,
  ColorConverterRoute: ColorConverterRoute,
  ColorExtractorRoute: ColorExtractorRoute,
  ColorHarmonyRoute: ColorHarmonyRoute,
  ColorPaletteRoute: ColorPaletteRoute,
  ColorPickerRoute: ColorPickerRoute,
  CookieParserRoute: CookieParserRoute,
  CronRoute: CronRoute,
  CronParserRoute: CronParserRoute,
  CssAnimationRoute: CssAnimationRoute,
  CssBorderRadiusRoute: CssBorderRadiusRoute,
  CssBoxShadowRoute: CssBoxShadowRoute,
  CssClipPathRoute: CssClipPathRoute,
  CssFilterRoute: CssFilterRoute,
  CssFlexboxRoute: CssFlexboxRoute,
  CssGradientRoute: CssGradientRoute,
  CssGridRoute: CssGridRoute,
  CssSpecificityRoute: CssSpecificityRoute,
  CssTextShadowRoute: CssTextShadowRoute,
  CssTransformRoute: CssTransformRoute,
  CssUnitRoute: CssUnitRoute,
  CsvJsonRoute: CsvJsonRoute,
  CurlBuilderRoute: CurlBuilderRoute,
  DiceRollRoute: DiceRollRoute,
  DiffRoute: DiffRoute,
  DiscordEmojiRoute: DiscordEmojiRoute,
  DiscordStickerRoute: DiscordStickerRoute,
  DnsLookupRoute: DnsLookupRoute,
  DummyAudioRoute: DummyAudioRoute,
  DummyImageRoute: DummyImageRoute,
  EmailDnsRoute: EmailDnsRoute,
  EmojiConverterRoute: EmojiConverterRoute,
  EnvParserRoute: EnvParserRoute,
  FaviconGeneratorRoute: FaviconGeneratorRoute,
  GitignoreRoute: GitignoreRoute,
  GlobalIpRoute: GlobalIpRoute,
  HashRoute: HashRoute,
  HexViewerRoute: HexViewerRoute,
  HtmlEncodeRoute: HtmlEncodeRoute,
  HtmlToJsxRoute: HtmlToJsxRoute,
  HttpClientRoute: HttpClientRoute,
  HttpHeadersRoute: HttpHeadersRoute,
  HttpStatusRoute: HttpStatusRoute,
  ImageBase64Route: ImageBase64Route,
  ImageCompressRoute: ImageCompressRoute,
  ImageCropRoute: ImageCropRoute,
  ImageResizeRoute: ImageResizeRoute,
  ImageToGifRoute: ImageToGifRoute,
  IpCidrCheckRoute: IpCidrCheckRoute,
  IpConverterRoute: IpConverterRoute,
  IpGeolocationRoute: IpGeolocationRoute,
  JsonRoute: JsonRoute,
  JsonCompareRoute: JsonCompareRoute,
  JsonPathRoute: JsonPathRoute,
  JsonSchemaRoute: JsonSchemaRoute,
  JsonToTsRoute: JsonToTsRoute,
  JwtRoute: JwtRoute,
  JwtGeneratorRoute: JwtGeneratorRoute,
  KeycodeRoute: KeycodeRoute,
  LoremIpsumRoute: LoremIpsumRoute,
  MarkdownPreviewRoute: MarkdownPreviewRoute,
  MarkdownTableRoute: MarkdownTableRoute,
  MathEvalRoute: MathEvalRoute,
  MermaidRoute: MermaidRoute,
  MimeTypesRoute: MimeTypesRoute,
  MinifyRoute: MinifyRoute,
  MorseCodeRoute: MorseCodeRoute,
  MsgpackRoute: MsgpackRoute,
  NumberBaseRoute: NumberBaseRoute,
  OgpRoute: OgpRoute,
  OpensslBuilderRoute: OpensslBuilderRoute,
  PasswordGeneratorRoute: PasswordGeneratorRoute,
  PhpSerializeRoute: PhpSerializeRoute,
  PomodoroRoute: PomodoroRoute,
  PortCheckRoute: PortCheckRoute,
  QrCodeRoute: QrCodeRoute,
  RandomDataRoute: RandomDataRoute,
  RegexCheckerRoute: RegexCheckerRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SecurityHeadersRoute: SecurityHeadersRoute,
  ServerEnvRoute: ServerEnvRoute,
  SlugRoute: SlugRoute,
  SqlRoute: SqlRoute,
  SvgOptimizerRoute: SvgOptimizerRoute,
  TextCaseRoute: TextCaseRoute,
  TextEncryptRoute: TextEncryptRoute,
  TextReplaceRoute: TextReplaceRoute,
  TextSortRoute: TextSortRoute,
  TextStatsRoute: TextStatsRoute,
  TimestampRoute: TimestampRoute,
  TimezoneRoute: TimezoneRoute,
  TomlJsonRoute: TomlJsonRoute,
  TopRoute: TopRoute,
  TotpRoute: TotpRoute,
  TransparentImageRoute: TransparentImageRoute,
  TypographyScaleRoute: TypographyScaleRoute,
  UnicodeRoute: UnicodeRoute,
  UnitConverterRoute: UnitConverterRoute,
  UrlEncodeRoute: UrlEncodeRoute,
  UrlParserRoute: UrlParserRoute,
  UserAgentRoute: UserAgentRoute,
  UuidRoute: UuidRoute,
  VideoConverterRoute: VideoConverterRoute,
  WhoisRoute: WhoisRoute,
  XmlRoute: XmlRoute,
  YamlJsonRoute: YamlJsonRoute,
  ApiImageDotjpgRoute: ApiImageDotjpgRoute,
  ApiImageDotpngRoute: ApiImageDotpngRoute,
  ApiImageDotsvgRoute: ApiImageDotsvgRoute,
  ApiImageDotwebpRoute: ApiImageDotwebpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
