/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoisRouteImport } from './routes/whois'
import { Route as UuidRouteImport } from './routes/uuid'
import { Route as UrlEncodeRouteImport } from './routes/url-encode'
import { Route as ServerEnvRouteImport } from './routes/server-env'
import { Route as RegexCheckerRouteImport } from './routes/regex-checker'
import { Route as PasswordGeneratorRouteImport } from './routes/password-generator'
import { Route as OgpRouteImport } from './routes/ogp'
import { Route as JwtRouteImport } from './routes/jwt'
import { Route as JsonRouteImport } from './routes/json'
import { Route as IpGeolocationRouteImport } from './routes/ip-geolocation'
import { Route as GlobalIpRouteImport } from './routes/global-ip'
import { Route as DummyAudioRouteImport } from './routes/dummy-audio'
import { Route as IndexRouteImport } from './routes/index'

const WhoisRoute = WhoisRouteImport.update({
  id: '/whois',
  path: '/whois',
  getParentRoute: () => rootRouteImport,
} as any)
const UuidRoute = UuidRouteImport.update({
  id: '/uuid',
  path: '/uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlEncodeRoute = UrlEncodeRouteImport.update({
  id: '/url-encode',
  path: '/url-encode',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerEnvRoute = ServerEnvRouteImport.update({
  id: '/server-env',
  path: '/server-env',
  getParentRoute: () => rootRouteImport,
} as any)
const RegexCheckerRoute = RegexCheckerRouteImport.update({
  id: '/regex-checker',
  path: '/regex-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordGeneratorRoute = PasswordGeneratorRouteImport.update({
  id: '/password-generator',
  path: '/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const OgpRoute = OgpRouteImport.update({
  id: '/ogp',
  path: '/ogp',
  getParentRoute: () => rootRouteImport,
} as any)
const JwtRoute = JwtRouteImport.update({
  id: '/jwt',
  path: '/jwt',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonRoute = JsonRouteImport.update({
  id: '/json',
  path: '/json',
  getParentRoute: () => rootRouteImport,
} as any)
const IpGeolocationRoute = IpGeolocationRouteImport.update({
  id: '/ip-geolocation',
  path: '/ip-geolocation',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalIpRoute = GlobalIpRouteImport.update({
  id: '/global-ip',
  path: '/global-ip',
  getParentRoute: () => rootRouteImport,
} as any)
const DummyAudioRoute = DummyAudioRouteImport.update({
  id: '/dummy-audio',
  path: '/dummy-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dummy-audio': typeof DummyAudioRoute
  '/global-ip': typeof GlobalIpRoute
  '/ip-geolocation': typeof IpGeolocationRoute
  '/json': typeof JsonRoute
  '/jwt': typeof JwtRoute
  '/ogp': typeof OgpRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/regex-checker': typeof RegexCheckerRoute
  '/server-env': typeof ServerEnvRoute
  '/url-encode': typeof UrlEncodeRoute
  '/uuid': typeof UuidRoute
  '/whois': typeof WhoisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dummy-audio': typeof DummyAudioRoute
  '/global-ip': typeof GlobalIpRoute
  '/ip-geolocation': typeof IpGeolocationRoute
  '/json': typeof JsonRoute
  '/jwt': typeof JwtRoute
  '/ogp': typeof OgpRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/regex-checker': typeof RegexCheckerRoute
  '/server-env': typeof ServerEnvRoute
  '/url-encode': typeof UrlEncodeRoute
  '/uuid': typeof UuidRoute
  '/whois': typeof WhoisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dummy-audio': typeof DummyAudioRoute
  '/global-ip': typeof GlobalIpRoute
  '/ip-geolocation': typeof IpGeolocationRoute
  '/json': typeof JsonRoute
  '/jwt': typeof JwtRoute
  '/ogp': typeof OgpRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/regex-checker': typeof RegexCheckerRoute
  '/server-env': typeof ServerEnvRoute
  '/url-encode': typeof UrlEncodeRoute
  '/uuid': typeof UuidRoute
  '/whois': typeof WhoisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dummy-audio'
    | '/global-ip'
    | '/ip-geolocation'
    | '/json'
    | '/jwt'
    | '/ogp'
    | '/password-generator'
    | '/regex-checker'
    | '/server-env'
    | '/url-encode'
    | '/uuid'
    | '/whois'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dummy-audio'
    | '/global-ip'
    | '/ip-geolocation'
    | '/json'
    | '/jwt'
    | '/ogp'
    | '/password-generator'
    | '/regex-checker'
    | '/server-env'
    | '/url-encode'
    | '/uuid'
    | '/whois'
  id:
    | '__root__'
    | '/'
    | '/dummy-audio'
    | '/global-ip'
    | '/ip-geolocation'
    | '/json'
    | '/jwt'
    | '/ogp'
    | '/password-generator'
    | '/regex-checker'
    | '/server-env'
    | '/url-encode'
    | '/uuid'
    | '/whois'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DummyAudioRoute: typeof DummyAudioRoute
  GlobalIpRoute: typeof GlobalIpRoute
  IpGeolocationRoute: typeof IpGeolocationRoute
  JsonRoute: typeof JsonRoute
  JwtRoute: typeof JwtRoute
  OgpRoute: typeof OgpRoute
  PasswordGeneratorRoute: typeof PasswordGeneratorRoute
  RegexCheckerRoute: typeof RegexCheckerRoute
  ServerEnvRoute: typeof ServerEnvRoute
  UrlEncodeRoute: typeof UrlEncodeRoute
  UuidRoute: typeof UuidRoute
  WhoisRoute: typeof WhoisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whois': {
      id: '/whois'
      path: '/whois'
      fullPath: '/whois'
      preLoaderRoute: typeof WhoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uuid': {
      id: '/uuid'
      path: '/uuid'
      fullPath: '/uuid'
      preLoaderRoute: typeof UuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url-encode': {
      id: '/url-encode'
      path: '/url-encode'
      fullPath: '/url-encode'
      preLoaderRoute: typeof UrlEncodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-env': {
      id: '/server-env'
      path: '/server-env'
      fullPath: '/server-env'
      preLoaderRoute: typeof ServerEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regex-checker': {
      id: '/regex-checker'
      path: '/regex-checker'
      fullPath: '/regex-checker'
      preLoaderRoute: typeof RegexCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-generator': {
      id: '/password-generator'
      path: '/password-generator'
      fullPath: '/password-generator'
      preLoaderRoute: typeof PasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ogp': {
      id: '/ogp'
      path: '/ogp'
      fullPath: '/ogp'
      preLoaderRoute: typeof OgpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwt': {
      id: '/jwt'
      path: '/jwt'
      fullPath: '/jwt'
      preLoaderRoute: typeof JwtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json': {
      id: '/json'
      path: '/json'
      fullPath: '/json'
      preLoaderRoute: typeof JsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-geolocation': {
      id: '/ip-geolocation'
      path: '/ip-geolocation'
      fullPath: '/ip-geolocation'
      preLoaderRoute: typeof IpGeolocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-ip': {
      id: '/global-ip'
      path: '/global-ip'
      fullPath: '/global-ip'
      preLoaderRoute: typeof GlobalIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dummy-audio': {
      id: '/dummy-audio'
      path: '/dummy-audio'
      fullPath: '/dummy-audio'
      preLoaderRoute: typeof DummyAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DummyAudioRoute: DummyAudioRoute,
  GlobalIpRoute: GlobalIpRoute,
  IpGeolocationRoute: IpGeolocationRoute,
  JsonRoute: JsonRoute,
  JwtRoute: JwtRoute,
  OgpRoute: OgpRoute,
  PasswordGeneratorRoute: PasswordGeneratorRoute,
  RegexCheckerRoute: RegexCheckerRoute,
  ServerEnvRoute: ServerEnvRoute,
  UrlEncodeRoute: UrlEncodeRoute,
  UuidRoute: UuidRoute,
  WhoisRoute: WhoisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
